services:
  - type: web
    name: ai-book-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
