import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const nonFictionBooks = [
    {
        title: "The Anxious Generation",
        author: "Jonathan Haidt",
        description: "Haidt argues that the rise in mental health issues among Gen Z is linked to their upbringing in a phone-based, social media-dominated environment.",
        price: 599,
        category: "Non-Fiction",
        genre: "Psychology",
        stock: 45,
        isbn: "9780593444400",
        pages: 400,
        language: "English",
        publishedDate: "2024-03-26",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593444400-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593444400-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Spare",
        author: "Prince Harry",
        description: "A candid memoir by Prince Harry, detailing his life, experiences, and perspective on the British Royal Family.",
        price: 749,
        category: "Non-Fiction",
        genre: "Memoir",
        stock: 30,
        isbn: "9780593593801",
        pages: 416,
        language: "English",
        publishedDate: "2023-01-10",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593593801-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593593801-L.jpg",
        bestseller: true
    },
    {
        title: "Atomic Habits",
        author: "James Clear",
        description: "A practical, actionable framework for improving every day, offering strategies for building good habits and breaking bad ones.",
        price: 499,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 120,
        isbn: "9780735211292",
        pages: 320,
        language: "English",
        publishedDate: "2018-10-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Sapiens",
        author: "Yuval Noah Harari",
        description: "A journey through the history of the human species, exploring how Homo sapiens came to dominate the world.",
        price: 549,
        category: "Non-Fiction",
        genre: "History",
        stock: 65,
        isbn: "9780062316097",
        pages: 443,
        language: "English",
        publishedDate: "2011-09-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
        bestseller: true
    },
    {
        title: "The Woman in Me",
        author: "Britney Spears",
        description: "A memoir by the pop icon Britney Spears, offering her perspective on her career, personal life, and experiences.",
        price: 699,
        category: "Non-Fiction",
        genre: "Memoir",
        stock: 25,
        isbn: "9781668009044",
        pages: 288,
        language: "English",
        publishedDate: "2023-10-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781668009044-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781668009044-L.jpg"
    },
    {
        title: "Hidden Potential",
        author: "Adam M. Grant",
        description: "Grant explores the science behind achieving greater things, moving beyond inherent talent to focus on unlocking potential.",
        price: 525,
        category: "Non-Fiction",
        genre: "Psychology",
        stock: 40,
        isbn: "9780593652829",
        pages: 320,
        language: "English",
        publishedDate: "2023-10-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593652829-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593652829-L.jpg"
    },
    {
        title: "Feel-Good Productivity",
        author: "Ali Abdaal",
        description: "Abdaal offers insights into how to increase productivity by focusing on enjoyment and meaning.",
        price: 449,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 50,
        isbn: "9780753559132",
        pages: 304,
        language: "English",
        publishedDate: "2023-12-28",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780753559132-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780753559132-L.jpg"
    },
    {
        title: "Oath and Honor",
        author: "Liz Cheney",
        description: "Liz Cheney's memoir provides her account of her time in Congress and the events surrounding January 6th.",
        price: 599,
        category: "Non-Fiction",
        genre: "Politics",
        stock: 20,
        isbn: "9781250871920",
        pages: 384,
        language: "English",
        publishedDate: "2023-12-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250871920-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250871920-L.jpg"
    },
    {
        title: "The Myth of Normal",
        author: "Gabor Maté",
        description: "Maté examines how Western culture's emphasis on normalcy can contribute to illness and trauma.",
        price: 499,
        category: "Non-Fiction",
        genre: "Health",
        stock: 35,
        isbn: "9781647896434",
        pages: 576,
        language: "English",
        publishedDate: "2022-09-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781647896434-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781647896434-L.jpg"
    },
    {
        title: "Killers of the Flower Moon",
        author: "David Grann",
        description: "True story of the murders of wealthy Osage Nation members and the birth of the FBI.",
        price: 399,
        category: "Non-Fiction",
        genre: "True Crime",
        stock: 60,
        isbn: "9780385534246",
        pages: 352,
        language: "English",
        publishedDate: "2017-04-18",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780385534246-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780385534246-L.jpg",
        bestseller: true
    },
    {
        title: "Nexus",
        author: "Yuval Noah Harari",
        description: "A brief history of information networks from the Stone Age to AI.",
        price: 649,
        category: "Non-Fiction",
        genre: "Philosophy",
        stock: 40,
        isbn: "9780593730077",
        pages: 528,
        language: "English",
        publishedDate: "2024-09-10",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593730077-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593730077-L.jpg",
        featured: true
    },
    {
        title: "Dopamine Nation",
        author: "Anna Lembke",
        description: "Finding balance in the age of indulgence and understanding addiction.",
        price: 425,
        category: "Non-Fiction",
        genre: "Health",
        stock: 55,
        isbn: "9781635766282",
        pages: 304,
        language: "English",
        publishedDate: "2021-08-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781635766282-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781635766282-L.jpg"
    },
    {
        title: "Supercommunicators",
        author: "Charles Duhigg",
        description: "How to unlock the secret language of connection and improve communication.",
        price: 549,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 45,
        isbn: "9780812984535",
        pages: 320,
        language: "English",
        publishedDate: "2024-02-20",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780812984535-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780812984535-L.jpg"
    },
    {
        title: "Becoming",
        author: "Michelle Obama",
        description: "Michelle Obama's personal memoir chronicles her life from childhood to First Lady.",
        price: 599,
        category: "Non-Fiction",
        genre: "Memoir",
        stock: 100,
        isbn: "9781524763135",
        pages: 448,
        language: "English",
        publishedDate: "2018-11-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781524763135-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781524763135-L.jpg",
        bestseller: true
    },
    {
        title: "Educated",
        author: "Tara Westover",
        description: "A memoir about a young girl who overcomes a survivalist upbringing to pursue an education.",
        price: 499,
        category: "Non-Fiction",
        genre: "Memoir",
        stock: 75,
        isbn: "9780399590504",
        pages: 352,
        language: "English",
        publishedDate: "2018-02-20",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
        bestseller: true
    },
    {
        title: "The Power of Habit",
        author: "Charles Duhigg",
        description: "Exploring the science behind habits and how they can be changed.",
        price: 399,
        category: "Non-Fiction",
        genre: "Psychology",
        stock: 80,
        isbn: "9780812981602",
        pages: 416,
        language: "English",
        publishedDate: "2012-02-28",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780812981602-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780812981602-L.jpg"
    },
    {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        description: "Explaining the two systems that drive our thinking and our cognitive biases.",
        price: 499,
        category: "Non-Fiction",
        genre: "Psychology",
        stock: 60,
        isbn: "9780374533557",
        pages: 499,
        language: "English",
        publishedDate: "2011-10-25",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg"
    },
    {
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen Covey",
        description: "A principle-centered approach for solving personal and professional problems.",
        price: 449,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 90,
        isbn: "9781982137274",
        pages: 432,
        language: "English",
        publishedDate: "1989-08-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
        bestseller: true
    },
    {
        title: "Quiet",
        author: "Susan Cain",
        description: "The power of introverts in a world that can't stop talking.",
        price: 399,
        category: "Non-Fiction",
        genre: "Social Science",
        stock: 55,
        isbn: "9780307352155",
        pages: 352,
        language: "English",
        publishedDate: "2012-01-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780307352155-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780307352155-L.jpg"
    },
    {
        title: "Grit",
        author: "Angela Duckworth",
        description: "The power of passion and perseverance as the key to success.",
        price: 425,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 65,
        isbn: "9781501110359",
        pages: 352,
        language: "English",
        publishedDate: "2016-05-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501110359-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501110359-L.jpg"
    },
    {
        title: "Thinking for Yourself",
        author: "Robin Reames",
        description: "The power of rhetoric in polarized times and how to think critically.",
        price: 479,
        category: "Non-Fiction",
        genre: "Philosophy",
        stock: 30,
        isbn: "9780593449399",
        pages: 288,
        language: "English",
        publishedDate: "2024-04-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593449399-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593449399-L.jpg"
    },
    {
        title: "A Day in the Life of Abed Salama",
        author: "Nathan Thrall",
        description: "A tragic story of a bus crash in Jerusalem and the broader conflict context.",
        price: 529,
        category: "Non-Fiction",
        genre: "Current Affairs",
        stock: 25,
        isbn: "9781635422891",
        pages: 272,
        language: "English",
        publishedDate: "2023-10-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781635422891-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781635422891-L.jpg"
    },
    {
        title: "Supremacy",
        author: "Parmy Olson",
        description: "AI, ChatGPT, and the race that will change the world.",
        price: 599,
        category: "Non-Fiction",
        genre: "Technology",
        stock: 40,
        isbn: "9781529380963",
        pages: 320,
        language: "English",
        publishedDate: "2024-06-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781529380963-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781529380963-L.jpg"
    },
    {
        title: "The Age of Magical Overthinking",
        author: "Amanda Montell",
        description: "Notes on modern irrationality and our cognitive biases.",
        price: 499,
        category: "Non-Fiction",
        genre: "Social Science",
        stock: 35,
        isbn: "9780593449337",
        pages: 288,
        language: "English",
        publishedDate: "2024-04-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593449337-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593449337-L.jpg"
    },
    {
        title: "Legacy",
        author: "Dr. Uché Blackstock",
        description: "A Black physician reckons with racism in medicine.",
        price: 479,
        category: "Non-Fiction",
        genre: "Health",
        stock: 30,
        isbn: "9780306830739",
        pages: 288,
        language: "English",
        publishedDate: "2024-01-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780306830739-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780306830739-L.jpg"
    },
    {
        title: "I Heard Her Call My Name",
        author: "Lucy Sante",
        description: "A memoir on artistic pursuits and understanding gender identity.",
        price: 549,
        category: "Non-Fiction",
        genre: "Memoir",
        stock: 20,
        isbn: "9780593447951",
        pages: 224,
        language: "English",
        publishedDate: "2024-02-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593447951-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593447951-L.jpg"
    },
    {
        title: "Man's Search for Meaning",
        author: "Viktor Frankl",
        description: "Finding meaning even in the most dire circumstances within concentration camps.",
        price: 299,
        category: "Non-Fiction",
        genre: "Psychology",
        stock: 100,
        isbn: "9780807014295",
        pages: 184,
        language: "English",
        publishedDate: "1946-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
        bestseller: true
    },
    {
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        description: "A counterintuitive approach to living a good life by prioritizing what matters.",
        price: 399,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 150,
        isbn: "9780062457714",
        pages: 224,
        language: "English",
        publishedDate: "2016-09-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
        bestseller: true
    },
    {
        title: "The Power of Now",
        author: "Eckhart Tolle",
        description: "A guide to spiritual enlightenment by living fully in the present moment.",
        price: 349,
        category: "Non-Fiction",
        genre: "Spirituality",
        stock: 90,
        isbn: "9781577314806",
        pages: 236,
        language: "English",
        publishedDate: "1997-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg"
    },
    {
        title: "Deep Work",
        author: "Cal Newport",
        description: "Rules for focused success in a distracted world.",
        price: 499,
        category: "Non-Fiction",
        genre: "Self-Help",
        stock: 70,
        isbn: "9781455586691",
        pages: 304,
        language: "English",
        publishedDate: "2016-01-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg"
    },
    {
        title: "The 4-Hour Workweek",
        author: "Timothy Ferriss",
        description: "Escape 9-5, live anywhere, and join the new rich.",
        price: 449,
        category: "Non-Fiction",
        genre: "Business",
        stock: 85,
        isbn: "9780307463639",
        pages: 416,
        language: "English",
        publishedDate: "2007-04-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780307463639-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780307463639-L.jpg"
    },
    {
        title: "Outliers",
        author: "Malcolm Gladwell",
        description: "The story of success and why some people achieve much more than others.",
        price: 399,
        category: "Non-Fiction",
        genre: "Psychology",
        stock: 95,
        isbn: "9780316017930",
        pages: 309,
        language: "English",
        publishedDate: "2008-11-18",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg",
        bestseller: true
    },
    {
        title: "Freakonomics",
        author: "Steven D. Levitt",
        description: "A rogue economist explores the hidden side of everything.",
        price: 299,
        category: "Non-Fiction",
        genre: "Economics",
        stock: 110,
        isbn: "9780060731328",
        pages: 320,
        language: "English",
        publishedDate: "2005-04-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060731328-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060731328-L.jpg"
    },
    {
        title: "The Tipping Point",
        author: "Malcolm Gladwell",
        description: "How little things can make a big difference in social trends.",
        price: 349,
        category: "Non-Fiction",
        genre: "Social Science",
        stock: 75,
        isbn: "9780316346627",
        pages: 301,
        language: "English",
        publishedDate: "2000-03-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316346627-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316346627-L.jpg"
    },
    {
        title: "Start with Why",
        author: "Simon Sinek",
        description: "How great leaders inspire everyone to take action by starting with why.",
        price: 499,
        category: "Non-Fiction",
        genre: "Leadership",
        stock: 60,
        isbn: "9781591846444",
        pages: 256,
        language: "English",
        publishedDate: "2009-10-29",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg"
    },
    {
        title: "The Emperor of All Maladies",
        author: "Siddhartha Mukherjee",
        description: "A magnificent, profoundly humane 'biography' of cancer.",
        price: 599,
        category: "Non-Fiction",
        genre: "Health",
        stock: 40,
        isbn: "9781439107959",
        pages: 571,
        language: "English",
        publishedDate: "2010-11-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781439107959-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781439107959-L.jpg",
        featured: true
    },
    {
        title: "The Immortal Life of Henrietta Lacks",
        author: "Rebecca Skloot",
        description: "The story of Henrietta Lacks and the first 'immortal' human cell line.",
        price: 449,
        category: "Non-Fiction",
        genre: "Science",
        stock: 50,
        isbn: "9781400052180",
        pages: 370,
        language: "English",
        publishedDate: "2010-02-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781400052180-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781400052180-L.jpg"
    },
    {
        title: "Factfulness",
        author: "Hans Rosling",
        description: "Ten reasons we're wrong about the world—and why things are better than you think.",
        price: 499,
        category: "Non-Fiction",
        genre: "Social Science",
        stock: 65,
        isbn: "9781250107817",
        pages: 352,
        language: "English",
        publishedDate: "2018-04-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250107817-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250107817-L.jpg",
        featured: true
    },
    {
        title: "Being Mortal",
        author: "Atul Gawande",
        description: "Medicine and what matters in the end, exploring aging and end-of-life care.",
        price: 399,
        category: "Non-Fiction",
        genre: "Health",
        stock: 55,
        isbn: "9780805095159",
        pages: 282,
        language: "English",
        publishedDate: "2014-10-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780805095159-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780805095159-L.jpg"
    },
    {
        title: "Why We Sleep",
        author: "Matthew Walker",
        description: "Unlocking the power of sleep and dreams for better health and productivity.",
        price: 499,
        category: "Non-Fiction",
        genre: "Health",
        stock: 60,
        isbn: "9781501144318",
        pages: 368,
        language: "English",
        publishedDate: "2017-10-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501144318-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501144318-L.jpg"
    }
];

const seedNonFiction = async () => {
    try {
        console.log('Seeding 40 Non-Fiction books...');
        await Book.insertMany(nonFictionBooks);
        console.log('Successfully seeded 40 non-fiction books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding non-fiction books:', error);
        process.exit(1);
    }
};

seedNonFiction();
