import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const fictionBooks = [
    {
        title: "Where the Crawdads Sing",
        author: "Delia Owens",
        description: "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl.",
        price: 499,
        category: "Fiction",
        genre: "Literary Fiction",
        stock: 55,
        isbn: "978-0735219090",
        pages: 368,
        language: "English",
        publishedDate: "2018-08-14",
        coverImage: "/uploads/books/crawdads_sing.png",
        featured: true,
        bestseller: true
    },
    {
        title: "The Seven Husbands of Evelyn Hugo",
        author: "Taylor Jenkins Reid",
        description: "Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself.",
        price: 449,
        category: "Fiction",
        genre: "Historical Fiction",
        stock: 45,
        isbn: "978-1501139239",
        pages: 400,
        language: "English",
        publishedDate: "2017-06-13",
        coverImage: "/uploads/books/evelyn_hugo.png",
        featured: true,
        bestseller: true
    },
    {
        title: "Circe",
        author: "Madeline Miller",
        description: "In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—not powerful, like her father, nor viciously alluring like her mother. Turning to the world of mortals for companionship, she discovers that she does possess power—the power of witchcraft.",
        price: 399,
        category: "Fiction",
        genre: "Mythological Fiction",
        stock: 50,
        isbn: "978-0316556347",
        pages: 393,
        language: "English",
        publishedDate: "2018-04-10",
        coverImage: "/uploads/books/circe.png",
        featured: true,
        bestseller: false
    },
    {
        title: "Normal People",
        author: "Sally Rooney",
        description: "Connell and Marianne grew up in the same small town, but the similarities end there. At school, Connell is popular and well-liked, while Marianne is a loner. But when the two strike up a conversation—awkward but electrifying—something life-changing begins.",
        price: 349,
        category: "Fiction",
        genre: "Contemporary Fiction",
        stock: 60,
        isbn: "978-1984822178",
        pages: 273,
        language: "English",
        publishedDate: "2018-08-28",
        coverImage: "/uploads/books/normal_people.png",
        featured: false,
        bestseller: true
    },
    {
        title: "The Song of Achilles",
        author: "Madeline Miller",
        description: "A thrilling, profound, and unexpectedly moving retelling of the Iliad, as told beneath the shadow of the walls of Troy.",
        price: 379,
        category: "Fiction",
        genre: "Mythological Fiction",
        stock: 40,
        isbn: "978-0062060624",
        pages: 378,
        language: "English",
        publishedDate: "2011-09-20",
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
        featured: true
    },
    {
        title: "Lessons in Chemistry",
        author: "Bonnie Garmus",
        description: "Chemist Elizabeth Zott is not your average woman. In fact, Elizabeth Zott would be the first to point out that there is no such thing as an average woman.",
        price: 499,
        category: "Fiction",
        genre: "Historical Fiction",
        stock: 35,
        isbn: "978-0385547345",
        pages: 400,
        language: "English",
        publishedDate: "2022-04-05",
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "Tomorrow, and Tomorrow, and Tomorrow",
        author: "Gabrielle Zevin",
        description: "Spanning thirty years, from Cambridge, Massachusetts, to Venice Beach, California, and lands in between and far beyond, Gabrielle Zevin’s Tomorrow, and Tomorrow, and Tomorrow is a dazzling and intricately imagined novel.",
        price: 425,
        category: "Fiction",
        genre: "Contemporary Fiction",
        stock: 30,
        isbn: "978-0593321201",
        pages: 416,
        language: "English",
        publishedDate: "2022-07-05",
        coverImage: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop",
        featured: true
    },
    {
        title: "Great Expectations",
        author: "Charles Dickens",
        description: "Pip, a young orphan, is endowed with 'great expectations' from an anonymous benefactor, but life takes many unexpected turns.",
        price: 199,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 80,
        isbn: "978-0141439563",
        pages: 544,
        language: "English",
        publishedDate: "1861-01-01",
        coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop"
    },
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        description: "A classic novel dealing with the themes of marriage, money, and love in 19th-century England.",
        price: 249,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 100,
        isbn: "978-0141439518",
        pages: 480,
        language: "English",
        publishedDate: "1813-01-28",
        coverImage: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "1984",
        author: "George Orwell",
        description: "A dystopian novel set in a totalitarian society where Big Brother is always watching.",
        price: 299,
        category: "Fiction",
        genre: "Dystopian Fiction",
        stock: 120,
        isbn: "978-0451524935",
        pages: 328,
        language: "English",
        publishedDate: "1949-06-08",
        coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
        featured: true,
        bestseller: true
    },
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
        price: 349,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 90,
        isbn: "978-0060935467",
        pages: 324,
        language: "English",
        publishedDate: "1960-07-11",
        coverImage: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "Little Women",
        author: "Louisa May Alcott",
        description: "The heartwarming story of the four March sisters growing up in Civil War-era New England.",
        price: 199,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 70,
        isbn: "978-0147514011",
        pages: 528,
        language: "English",
        publishedDate: "1868-09-30",
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop"
    },
    {
        title: "Frankenstein",
        author: "Mary Shelley",
        description: "The story of Victor Frankenstein and the monster he creates in a scientific experiment gone wrong.",
        price: 179,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 50,
        isbn: "978-0141439471",
        pages: 288,
        language: "English",
        publishedDate: "1818-01-01",
        coverImage: "https://images.unsplash.com/photo-1614544048536-0d28caf77f41?w=400&h=600&fit=crop"
    },
    {
        title: "Wuthering Heights",
        author: "Emily Brontë",
        description: "A powerful tale of love and revenge on the Yorkshire moors.",
        price: 225,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 45,
        isbn: "978-0141439556",
        pages: 416,
        language: "English",
        publishedDate: "1847-12-01",
        coverImage: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop"
    },
    {
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        description: "The story of Jane Eyre's growth into adulthood and her love for Mr. Rochester.",
        price: 249,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 55,
        isbn: "978-0141441146",
        pages: 592,
        language: "English",
        publishedDate: "1847-10-16",
        coverImage: "https://images.unsplash.com/photo-1618666012174-83b441c0bc76?w=400&h=600&fit=crop"
    },
    {
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        description: "A philosophical novel that explores the corruption of an innocent soul in 19th-century London.",
        price: 199,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 40,
        isbn: "978-0141439570",
        pages: 256,
        language: "English",
        publishedDate: "1890-06-20",
        coverImage: "https://images.unsplash.com/photo-1554774853-aae0a22c8aa4?w=400&h=600&fit=crop"
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        description: "A coming-of-age novel told from the perspective of Holden Caulfield.",
        price: 299,
        category: "Fiction",
        genre: "Classic Literature",
        stock: 65,
        isbn: "978-0316769488",
        pages: 277,
        language: "English",
        publishedDate: "1951-07-16",
        coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "Beloved",
        author: "Toni Morrison",
        description: "A powerful novel that explores the legacy of slavery and the bonds of family.",
        price: 349,
        category: "Fiction",
        genre: "Literary Fiction",
        stock: 35,
        isbn: "978-1400033416",
        pages: 324,
        language: "English",
        publishedDate: "1987-09-16",
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
        featured: true
    },
    {
        title: "One Hundred Years of Solitude",
        author: "Gabriel García Márquez",
        description: "A multi-generational story of the Buendía family in the fictional town of Macondo.",
        price: 449,
        category: "Fiction",
        genre: "Magical Realism",
        stock: 30,
        isbn: "978-0060883287",
        pages: 417,
        language: "English",
        publishedDate: "1967-05-30",
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        description: "A story of friendship, betrayal, and redemption set in Afghanistan.",
        price: 399,
        category: "Fiction",
        genre: "Literary Fiction",
        stock: 50,
        isbn: "978-1594631931",
        pages: 371,
        language: "English",
        publishedDate: "2003-05-29",
        coverImage: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "Life of Pi",
        author: "Yann Martel",
        description: "A fantasy adventure novel about a young boy surviving a shipwreck with a Bengal tiger.",
        price: 299,
        category: "Fiction",
        genre: "Adventure Fiction",
        stock: 60,
        isbn: "978-0156027328",
        pages: 460,
        language: "English",
        publishedDate: "2001-09-11",
        coverImage: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&h=600&fit=crop"
    },
    {
        title: "The Road",
        author: "Cormac McCarthy",
        description: "A post-apocalyptic novel about a father and son's journey across a desolate landscape.",
        price: 325,
        category: "Fiction",
        genre: "Post-Apocalyptic Fiction",
        stock: 40,
        isbn: "978-0307387899",
        pages: 287,
        language: "English",
        publishedDate: "2006-09-26",
        coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
        featured: true
    },
    {
        title: "Never Let Me Go",
        author: "Kazuo Ishiguro",
        description: "A dystopian novel that explores themes of humanity, memory, and morality.",
        price: 349,
        category: "Fiction",
        genre: "Science Fiction",
        stock: 45,
        isbn: "978-1400078776",
        pages: 288,
        language: "English",
        publishedDate: "2005-04-05",
        coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop"
    },
    {
        title: "A Thousand Splendid Suns",
        author: "Khaled Hosseini",
        description: "A moving story of the lives of two Afghan women spanning thirty years.",
        price: 399,
        category: "Fiction",
        genre: "Literary Fiction",
        stock: 50,
        isbn: "978-1594489501",
        pages: 372,
        language: "English",
        publishedDate: "2007-05-22",
        coverImage: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop",
        bestseller: true
    },
    {
        title: "The Night Circus",
        author: "Erin Morgenstern",
        description: "A fantasy novel about a magical circus and the two young magicians caught in a deadly competition.",
        price: 375,
        category: "Fiction",
        genre: "Fantasy Fiction",
        stock: 40,
        isbn: "978-0307744432",
        pages: 387,
        language: "English",
        publishedDate: "2011-09-13",
        coverImage: "https://images.unsplash.com/photo-1614544048536-0d28caf77f41?w=400&h=600&fit=crop",
        featured: true
    }
];

const seedFiction = async () => {
    try {
        console.log('Seeding 25 new Fiction books...');
        await Book.insertMany(fictionBooks);
        console.log('Successfully seeded 25 fiction books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding fiction books:', error);
        process.exit(1);
    }
};

seedFiction();
