import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const coverImgPlaceholder = "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400&auto=format&fit=crop";

const tamilLiteratureBooks = [
    {
        title: "Ponniyin Selvan - Part 1: Pudhu Vellam",
        author: "Kalki Krishnamurthy",
        description: "The classic historical novel that tells the story of early days of Arulmozhivarman, who later became the great Chola emperor Rajaraja Chola I.",
        price: 299,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 100,
        pages: 350,
        language: "Tamil",
        publishedDate: "1950-01-01",
        publisher: "Vikatan Prasuram",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        featured: true,
        bestseller: true
    },
    {
        title: "Ponniyin Selvan - Part 2: Suzhal Kaatru",
        author: "Kalki Krishnamurthy",
        description: "The second part of the historical masterpiece capturing the majestic Chola empire, politics, and power struggles.",
        price: 320,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 80,
        pages: 360,
        language: "Tamil",
        publishedDate: "1951-01-01",
        publisher: "Vikatan Prasuram",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Ponniyin Selvan - Part 3: Kolai Vaal",
        author: "Kalki Krishnamurthy",
        description: "The gripping third volume depicting assassinations plots and unexpected turns in the Chola dynasty.",
        price: 310,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 75,
        pages: 340,
        language: "Tamil",
        publishedDate: "1952-01-01",
        publisher: "Vikatan Prasuram",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Ponniyin Selvan - Part 4: Mani Magudam",
        author: "Kalki Krishnamurthy",
        description: "The fourth installment detailing the struggle for the crown and immense political tension.",
        price: 330,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 90,
        pages: 320,
        language: "Tamil",
        publishedDate: "1953-01-01",
        publisher: "Vikatan Prasuram",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Ponniyin Selvan - Part 5: Thiyaga Sigaram",
        author: "Kalki Krishnamurthy",
        description: "The grand conclusion of the Ponniyin Selvan saga crowning continuous sacrifices.",
        price: 350,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 85,
        pages: 400,
        language: "Tamil",
        publishedDate: "1954-01-01",
        publisher: "Vikatan Prasuram",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Sivagamiyin Sabatham",
        author: "Kalki Krishnamurthy",
        description: "A profound tale of the Pallava dynasty focusing on Narasimhavarman I and the dancer Sivagami.",
        price: 499,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 60,
        pages: 940,
        language: "Tamil",
        publishedDate: "1944-01-01",
        publisher: "Vanathi Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        featured: true
    },
    {
        title: "Parthiban Kanavu",
        author: "Kalki Krishnamurthy",
        description: "A historical novel which deals with the attempts of the son of Chola king Parthiban to attain independence.",
        price: 199,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 120,
        pages: 250,
        language: "Tamil",
        publishedDate: "1941-01-01",
        publisher: "Vanathi Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Alai Osai",
        author: "Kalki Krishnamurthy",
        description: "A story set during India's freedom struggle detailing the social and political changes.",
        price: 450,
        category: "Tamil Literature",
        genre: "Classic Fiction",
        stock: 50,
        pages: 820,
        language: "Tamil",
        publishedDate: "1948-01-01",
        publisher: "Kavitha Publication",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Kadal Pura",
        author: "Sandilyan",
        description: "A marine historical novel outlining the naval history of the Cholas.",
        price: 599,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 75,
        pages: 1100,
        language: "Tamil",
        publishedDate: "1967-01-01",
        publisher: "Vanathi Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Yavana Rani",
        author: "Sandilyan",
        description: "Another brilliant historical piece by Sandilyan revolving around Karikala Chola.",
        price: 549,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 80,
        pages: 980,
        language: "Tamil",
        publishedDate: "1960-01-01",
        publisher: "Vanathi Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Mannan Magal",
        author: "Sandilyan",
        description: "An adventurous romance set against the backdrop of an invasion.",
        price: 420,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 40,
        pages: 600,
        language: "Tamil",
        publishedDate: "1958-01-01",
        publisher: "Vanathi Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Jala Deepam",
        author: "Sandilyan",
        description: "The daring ocean voyages of the Tamil ancestors woven into a gripping story.",
        price: 380,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 45,
        pages: 560,
        language: "Tamil",
        publishedDate: "1973-01-01",
        publisher: "Vanathi Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Vengayin Maindhan",
        author: "Akilan",
        description: "A masterpiece that secured the Sahitya Akademi Award, describing the expansion of the Cholas.",
        price: 450,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 90,
        pages: 650,
        language: "Tamil",
        publishedDate: "1961-01-01",
        publisher: "Poompuhar Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Chithira Pavai",
        author: "Akilan",
        description: "A Jnanpith Award winning contemporary socio-romantic novel portraying changing societal norms.",
        price: 320,
        category: "Tamil Literature",
        genre: "Contemporary Fiction",
        stock: 65,
        pages: 420,
        language: "Tamil",
        publishedDate: "1968-01-01",
        publisher: "Poompuhar Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Kayalvizhi",
        author: "Akilan",
        description: "A historical romance exploring the depths of love, loyalty and statecraft.",
        price: 280,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 55,
        pages: 350,
        language: "Tamil",
        publishedDate: "1965-01-01",
        publisher: "Poompuhar Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Sila Nerangalil Sila Manithargal",
        author: "Jayakanthan",
        description: "A powerful critique on conservative society and its unjust treatments toward women.",
        price: 250,
        category: "Tamil Literature",
        genre: "Social Realism",
        stock: 150,
        pages: 290,
        language: "Tamil",
        publishedDate: "1970-01-01",
        publisher: "Meenakshi Puthaka Nilayam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        featured: true
    },
    {
        title: "Oru Nadigai Natakam Parkiral",
        author: "Jayakanthan",
        description: "A profound look into the lives of artists and their internal realities.",
        price: 210,
        category: "Tamil Literature",
        genre: "Social Realism",
        stock: 50,
        pages: 220,
        language: "Tamil",
        publishedDate: "1971-01-01",
        publisher: "Meenakshi Puthaka Nilayam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Oru Manithan Oru Veedu Oru Ulagam",
        author: "Jayakanthan",
        description: "An introspective journey mapping an individual's struggle to find his place in society.",
        price: 240,
        category: "Tamil Literature",
        genre: "Social Realism",
        stock: 75,
        pages: 240,
        language: "Tamil",
        publishedDate: "1973-01-01",
        publisher: "Meenakshi Puthaka Nilayam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Yaarukkaga Azhudhaan",
        author: "Jayakanthan",
        description: "A moving narration of poverty, guilt and the complexities of human compassion.",
        price: 180,
        category: "Tamil Literature",
        genre: "Social Realism",
        stock: 80,
        pages: 150,
        language: "Tamil",
        publishedDate: "1966-01-01",
        publisher: "Meenakshi Puthaka Nilayam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "En Iniya Iyenthira",
        author: "Sujatha",
        description: "A ground-breaking sci-fi thriller depicting a dystopian future dictating human affairs.",
        price: 280,
        category: "Tamil Literature",
        genre: "Science Fiction",
        stock: 120,
        pages: 310,
        language: "Tamil",
        publishedDate: "1980-01-01",
        publisher: "Uyirmmai Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        featured: true
    },
    {
        title: "Meendum Jeeno",
        author: "Sujatha",
        description: "The thrilling sequel expanding upon the technological singularity and robotic rebellion.",
        price: 300,
        category: "Tamil Literature",
        genre: "Science Fiction",
        stock: 110,
        pages: 340,
        language: "Tamil",
        publishedDate: "1984-01-01",
        publisher: "Uyirmmai Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Karaiyellam Shenbagapoo",
        author: "Sujatha",
        description: "A romantic mystery set in a village, revolving around a researcher's quest.",
        price: 250,
        category: "Tamil Literature",
        genre: "Mystery",
        stock: 90,
        pages: 280,
        language: "Tamil",
        publishedDate: "1981-01-01",
        publisher: "Kizhakku Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Srirangathu Devathaigal",
        author: "Sujatha",
        description: "Nostalgic and emotional stories reflecting life and characters in the temple town of Srirangam.",
        price: 210,
        category: "Tamil Literature",
        genre: "Short Stories",
        stock: 130,
        pages: 200,
        language: "Tamil",
        publishedDate: "2000-01-01",
        publisher: "Uyirmmai Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Aram",
        author: "Jeyamohan",
        description: "A collection of highly acclaimed short stories deeply grounded in morality and human dignity.",
        price: 350,
        category: "Tamil Literature",
        genre: "Short Stories",
        stock: 150,
        pages: 380,
        language: "Tamil",
        publishedDate: "2011-01-01",
        publisher: "Sol Vanam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Vishnupuram",
        author: "Jeyamohan",
        description: "A massive philosophical and mythological novel exploring Indian thought and spiritual quest.",
        price: 799,
        category: "Tamil Literature",
        genre: "Philosophical Fiction",
        stock: 40,
        pages: 750,
        language: "Tamil",
        publishedDate: "1997-01-01",
        publisher: "Kavitha Publication",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Venmurasu - Mutham",
        author: "Jeyamohan",
        description: "The first part of the monumental retelling of the Indian epic Mahabharata.",
        price: 450,
        category: "Tamil Literature",
        genre: "Mythology",
        stock: 60,
        pages: 400,
        language: "Tamil",
        publishedDate: "2014-01-01",
        publisher: "Natrinai",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Oru Puliyamarathin Kathai",
        author: "Sundara Ramaswamy",
        description: "An allegory describing the changing landscapes of Indian villages to modernity through a tamarind tree.",
        price: 220,
        category: "Tamil Literature",
        genre: "Classic Fiction",
        stock: 80,
        pages: 250,
        language: "Tamil",
        publishedDate: "1966-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "J.J. Sila Kurippugal",
        author: "Sundara Ramaswamy",
        description: "A seminal modernist work presenting the diary of a progressive Malayalam writer.",
        price: 260,
        category: "Tamil Literature",
        genre: "Modernist Fiction",
        stock: 75,
        pages: 310,
        language: "Tamil",
        publishedDate: "1981-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        featured: true
    },
    {
        title: "Karukku",
        author: "Bama",
        description: "An autobiographical novel shedding light on the struggles of Dalit Christian women.",
        price: 180,
        category: "Tamil Literature",
        genre: "Autobiography",
        stock: 120,
        pages: 150,
        language: "Tamil",
        publishedDate: "1992-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Sangathi",
        author: "Bama",
        description: "Focusing on community identities and resilience of marginalized women.",
        price: 160,
        category: "Tamil Literature",
        genre: "Social Realism",
        stock: 100,
        pages: 140,
        language: "Tamil",
        publishedDate: "1994-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Kuruthipunal",
        author: "Indira Parthasarathy",
        description: "Based on the Keezhvenmani massacre, portraying the agrarian crisis and communist uprising.",
        price: 220,
        category: "Tamil Literature",
        genre: "Political Fiction",
        stock: 65,
        pages: 200,
        language: "Tamil",
        publishedDate: "1975-01-01",
        publisher: "Kizhaku Pathippagam",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Vethala Ulagam",
        author: "Pudhumaipithan",
        description: "A magical and strange world explored through unique narrative techniques.",
        price: 150,
        category: "Tamil Literature",
        genre: "Classic Fiction",
        stock: 80,
        pages: 160,
        language: "Tamil",
        publishedDate: "1940-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Pudhumaipithan Kathaigal",
        author: "Pudhumaipithan",
        description: "A collection of stories from the pioneer of modern Tamil literature.",
        price: 280,
        category: "Tamil Literature",
        genre: "Short Stories",
        stock: 110,
        pages: 350,
        language: "Tamil",
        publishedDate: "1950-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true
    },
    {
        title: "Moga Mul",
        author: "Thi. Janakiraman",
        description: "An evocative romance charting music, passion, and emotional maturity.",
        price: 360,
        category: "Tamil Literature",
        genre: "Romance / Drama",
        stock: 75,
        pages: 560,
        language: "Tamil",
        publishedDate: "1956-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Amma Vandhaal",
        author: "Thi. Janakiraman",
        description: "A psychological domestic drama unraveling complex family dynamics and secrets.",
        price: 220,
        category: "Tamil Literature",
        genre: "Drama",
        stock: 50,
        pages: 280,
        language: "Tamil",
        publishedDate: "1960-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Gopallapuram",
        author: "Ki. Rajanarayanan",
        description: "Capturing the stark realities, myths, and legends of the Karisal (black soil) region.",
        price: 240,
        category: "Tamil Literature",
        genre: "Regional Fiction",
        stock: 90,
        pages: 300,
        language: "Tamil",
        publishedDate: "1976-01-01",
        publisher: "Annam Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Karisal Kathaigal",
        author: "Ki. Rajanarayanan",
        description: "Brilliant short stories echoing the native dialects and rural lifestyle of the South.",
        price: 200,
        category: "Tamil Literature",
        genre: "Short Stories",
        stock: 85,
        pages: 250,
        language: "Tamil",
        publishedDate: "1980-01-01",
        publisher: "Annam Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Velpari",
        author: "Su. Venkatesan",
        description: "An epic tale of a legendary tribal king Pari, his extraordinary courage and environmental harmony.",
        price: 750,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 140,
        pages: 1200,
        language: "Tamil",
        publishedDate: "2018-01-01",
        publisher: "Vikatan Prasuram",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder,
        bestseller: true,
        featured: true
    },
    {
        title: "Kaval Kottam",
        author: "Su. Venkatesan",
        description: "A colossal historical novel mapping the history of Madurai over six centuries.",
        price: 800,
        category: "Tamil Literature",
        genre: "Historical Fiction",
        stock: 70,
        pages: 1050,
        language: "Tamil",
        publishedDate: "2008-01-01",
        publisher: "Thamizhini",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    },
    {
        title: "Thanneer",
        author: "Ashokamitran",
        description: "A nuanced novel portraying middle-class life and struggles in an urban setting during a water crisis.",
        price: 180,
        category: "Tamil Literature",
        genre: "Social Realism",
        stock: 50,
        pages: 160,
        language: "Tamil",
        publishedDate: "1973-01-01",
        publisher: "Kalachuvadu Publications",
        coverImage: coverImgPlaceholder,
        image_url: coverImgPlaceholder
    }
];

const seedTamilLiterature = async () => {
    try {
        console.log('Seeding 40 Tamil Literature books...');
        await Book.insertMany(tamilLiteratureBooks);
        console.log('Successfully seeded 40 Tamil Literature books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding Tamil Literature books:', error);
        process.exit(1);
    }
};

seedTamilLiterature();
