import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const sciFiBooks = [
    {
        title: "The Ministry of Time",
        author: "Kaliane Bradley",
        description: "A near-future London civil servant monitoring a 'temporal expat' from the Victorian era as part of a mysterious government initiative.",
        price: 549,
        category: "Science Fiction",
        genre: "Time Travel",
        stock: 35,
        isbn: "9781668045145",
        pages: 352,
        language: "English",
        publishedDate: "2024-05-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781668045145-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781668045145-L.jpg",
        featured: true
    },
    {
        title: "Some Desperate Glory",
        author: "Emily Tesh",
        description: "A queer space opera where humanity, after Earth's destruction, trains young warriors to fight back against alien oppressors.",
        price: 499,
        category: "Science Fiction",
        genre: "Space Opera",
        stock: 40,
        isbn: "9781250834980",
        pages: 448,
        language: "English",
        publishedDate: "2023-04-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250834980-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250834980-L.jpg"
    },
    {
        title: "Translation State",
        author: "Ann Leckie",
        description: "Set in the Imperial Radch universe, exploring themes of belonging and the complexities of alien interaction.",
        price: 525,
        category: "Science Fiction",
        genre: "Space Opera",
        stock: 30,
        isbn: "9780316289719",
        pages: 432,
        language: "English",
        publishedDate: "2023-06-06",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316289719-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316289719-L.jpg"
    },
    {
        title: "Juice",
        author: "Tim Winton",
        description: "An epic post-apocalyptic thriller set in a ravaged future Australia.",
        price: 599,
        category: "Science Fiction",
        genre: "Post-Apocalyptic",
        stock: 25,
        isbn: "9781761344893",
        pages: 512,
        language: "English",
        publishedDate: "2024-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781761344893-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781761344893-L.jpg"
    },
    {
        title: "The Mercy of Gods",
        author: "James S.A. Corey",
        description: "From the authors of The Expanse, a new trilogy about human captives under alien rule.",
        price: 649,
        category: "Science Fiction",
        genre: "Space Opera",
        stock: 45,
        isbn: "9780316525572",
        pages: 432,
        language: "English",
        publishedDate: "2024-08-06",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316525572-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316525572-L.jpg",
        featured: true
    },
    {
        title: "Alien Clay",
        author: "Adrian Tchaikovsky",
        description: "A dissident exiled to a prison planet discovers humanity was not the first intelligent life.",
        price: 549,
        category: "Science Fiction",
        genre: "Sci-Fi Thriller",
        stock: 50,
        isbn: "9780316578967",
        pages: 400,
        language: "English",
        publishedDate: "2024-03-28",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316578967-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316578967-L.jpg"
    },
    {
        title: "Dune",
        author: "Frank Herbert",
        description: "The epic saga of Paul Atreides and the desert planet Arrakis.",
        price: 499,
        category: "Science Fiction",
        genre: "Epic Sci-Fi",
        stock: 150,
        isbn: "9780441172719",
        pages: 612,
        language: "English",
        publishedDate: "1965-06-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Project Hail Mary",
        author: "Andy Weir",
        description: "A lone astronaut must save the Earth from an extinction-level threat.",
        price: 525,
        category: "Science Fiction",
        genre: "Hard Sci-Fi",
        stock: 80,
        isbn: "9780593135204",
        pages: 496,
        language: "English",
        publishedDate: "2021-05-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
        bestseller: true
    },
    {
        title: "The Three-Body Problem",
        author: "Cixin Liu",
        description: "A breakthrough epic about humanity's first contact with an alien civilization.",
        price: 449,
        category: "Science Fiction",
        genre: "Hard Sci-Fi",
        stock: 70,
        isbn: "9780765377067",
        pages: 400,
        language: "English",
        publishedDate: "2008-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780765377067-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780765377067-L.jpg",
        bestseller: true
    },
    {
        title: "Neuromancer",
        author: "William Gibson",
        description: "The definitive cyberpunk novel that defined a generation.",
        price: 399,
        category: "Science Fiction",
        genre: "Cyberpunk",
        stock: 60,
        isbn: "9780441569595",
        pages: 271,
        language: "English",
        publishedDate: "1984-07-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg"
    },
    {
        title: "The Left Hand of Darkness",
        author: "Ursula K. Le Guin",
        description: "Exploring themes of gender and society on a distant, icy planet.",
        price: 349,
        category: "Science Fiction",
        genre: "Soft Sci-Fi",
        stock: 55,
        isbn: "9780441478125",
        pages: 304,
        language: "English",
        publishedDate: "1969-03-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg"
    },
    {
        title: "Foundation",
        author: "Isaac Asimov",
        description: "The start of the epic series about the fall and rebirth of a galactic empire.",
        price: 425,
        category: "Science Fiction",
        genre: "Classic Sci-Fi",
        stock: 90,
        isbn: "9780553293357",
        pages: 244,
        language: "English",
        publishedDate: "1951-05-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
        bestseller: true
    },
    {
        title: "Ready Player One",
        author: "Ernest Cline",
        description: "A quest for an Easter egg in a massive virtual reality world.",
        price: 399,
        category: "Science Fiction",
        genre: "Cyberpunk",
        stock: 120,
        isbn: "9780307887436",
        pages: 374,
        language: "English",
        publishedDate: "2011-08-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780307887436-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780307887436-L.jpg",
        bestseller: true
    },
    {
        title: "The Martian",
        author: "Andy Weir",
        description: "An astronaut stranded on Mars must use his ingenuity to survive.",
        price: 449,
        category: "Science Fiction",
        genre: "Hard Sci-Fi",
        stock: 100,
        isbn: "9780553418026",
        pages: 369,
        language: "English",
        publishedDate: "2011-09-27",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
        bestseller: true
    },
    {
        title: "Brave New World",
        author: "Aldous Huxley",
        description: "A vision of a futuristic society controlled by conditioning and pleasure.",
        price: 299,
        category: "Science Fiction",
        genre: "Dystopian",
        stock: 85,
        isbn: "9780060850524",
        pages: 268,
        language: "English",
        publishedDate: "1932-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg"
    },
    {
        title: "Fahrenheit 451",
        author: "Ray Bradbury",
        description: "A society where books are outlawed and 'firemen' burn any that are found.",
        price: 349,
        category: "Science Fiction",
        genre: "Dystopian",
        stock: 75,
        isbn: "9781451673319",
        pages: 158,
        language: "English",
        publishedDate: "1953-10-19",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
        bestseller: true
    },
    {
        title: "Snow Crash",
        author: "Neal Stephenson",
        description: "A fast-paced cyberpunk adventure in a fragmented future America.",
        price: 499,
        category: "Science Fiction",
        genre: "Cyberpunk",
        stock: 65,
        isbn: "9780553380958",
        pages: 470,
        language: "English",
        publishedDate: "1992-06-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553380958-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553380958-L.jpg"
    },
    {
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        description: "The comedic adventures of Arthur Dent through space and time.",
        price: 399,
        category: "Science Fiction",
        genre: "Comedy Sci-Fi",
        stock: 130,
        isbn: "9780345391803",
        pages: 216,
        language: "English",
        publishedDate: "1979-10-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
        bestseller: true
    },
    {
        title: "Ender's Game",
        author: "Orson Scott Card",
        description: "A young genius is trained to lead humanity's fleet against an alien threat.",
        price: 425,
        category: "Science Fiction",
        genre: "Military Sci-Fi",
        stock: 110,
        isbn: "9780812550702",
        pages: 324,
        language: "English",
        publishedDate: "1985-01-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg",
        bestseller: true
    },
    {
        title: "Leviathan Wakes",
        author: "James S.A. Corey",
        description: "The first book in The Expanse series, blending space opera and noir mystery.",
        price: 479,
        category: "Science Fiction",
        genre: "Space Opera",
        stock: 80,
        isbn: "9780316129084",
        pages: 592,
        language: "English",
        publishedDate: "2011-06-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316129084-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316129084-L.jpg",
        featured: true
    },
    {
        title: "Seveneves",
        author: "Neal Stephenson",
        description: "Humanity's struggle for survival after the moon unexpectedly explodes.",
        price: 599,
        category: "Science Fiction",
        genre: "Hard Sci-Fi",
        stock: 45,
        isbn: "9780062334510",
        pages: 880,
        language: "English",
        publishedDate: "2015-05-19",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062334510-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062334510-L.jpg"
    },
    {
        title: "All Systems Red",
        author: "Martha Wells",
        description: "The first installment of The Murderbot Diaries, featuring a reluctant AI security unit.",
        price: 349,
        category: "Science Fiction",
        genre: "Sci-Fi Adventure",
        stock: 70,
        isbn: "9780765397522",
        pages: 144,
        language: "English",
        publishedDate: "2017-05-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780765397522-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780765397522-L.jpg",
        bestseller: true
    },
    {
        title: "Service Model",
        author: "Adrian Tchaikovsky",
        description: "A satirical novel about a robotic valet who murders his master and seeks meaning.",
        price: 549,
        category: "Science Fiction",
        genre: "Satirical Sci-Fi",
        stock: 35,
        isbn: "9781250290281",
        pages: 400,
        language: "English",
        publishedDate: "2024-06-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250290281-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250290281-L.jpg"
    },
    {
        title: "The Last Murder at the End of the World",
        author: "Stuart Turton",
        description: "A mind-bending mystery set on an island at the end of the world.",
        price: 525,
        category: "Science Fiction",
        genre: "Sci-Fi Mystery",
        stock: 40,
        isbn: "9781705084922",
        pages: 368,
        language: "English",
        publishedDate: "2024-05-21",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781705084922-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781705084922-L.jpg"
    },
    {
        title: "Immortal Dark",
        author: "Tigest Girma",
        description: "A dark academia fantasy where a lost heiress infiltrates an arcane society.",
        price: 599,
        category: "Science Fiction",
        genre: "Dark Academia",
        stock: 30,
        isbn: "9780316570398",
        pages: 432,
        language: "English",
        publishedDate: "2024-09-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316570398-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316570398-L.jpg"
    },
    {
        title: "The Familiar",
        author: "Leigh Bardugo",
        description: "Historical fantasy set in 16th century Madrid, following Luzia and her 'little miracles'.",
        price: 649,
        category: "Science Fiction",
        genre: "Historical Fantasy",
        stock: 50,
        isbn: "9781250884251",
        pages: 400,
        language: "English",
        publishedDate: "2024-04-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250884251-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250884251-L.jpg",
        featured: true
    },
    {
        title: "Orbital",
        author: "Samantha Harvey",
        description: "A literary science fiction novel set on a space station, reflecting on human life.",
        price: 499,
        category: "Science Fiction",
        genre: "Literary Sci-Fi",
        stock: 25,
        isbn: "9780802161543",
        pages: 224,
        language: "English",
        publishedDate: "2023-11-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780802161543-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780802161543-L.jpg"
    },
    {
        title: "Annie Bot",
        author: "Sierra Greer",
        description: "Exploring themes of artificial intelligence and human relationships.",
        price: 529,
        category: "Science Fiction",
        genre: "Soft Sci-Fi",
        stock: 30,
        isbn: "9780063312692",
        pages: 256,
        language: "English",
        publishedDate: "2024-03-19",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780063312692-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780063312692-L.jpg"
    },
    {
        title: "The Family Experiment",
        author: "John Marrs",
        description: "A dark speculative thriller where couples raise virtual children in a reality show.",
        price: 579,
        category: "Science Fiction",
        genre: "Speculative Thriller",
        stock: 45,
        isbn: "9781538765470",
        pages: 400,
        language: "English",
        publishedDate: "2024-05-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781538765470-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781538765470-L.jpg"
    },
    {
        title: "Blade Runner",
        author: "Philip K. Dick",
        description: "Do Androids Dream of Electric Sheep? The classic story of identity and humanity.",
        price: 349,
        category: "Science Fiction",
        genre: "Cyberpunk",
        stock: 80,
        isbn: "9780345404473",
        pages: 210,
        language: "English",
        publishedDate: "1968-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780345404473-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780345404473-L.jpg",
        bestseller: true
    },
    {
        title: "Hyperion",
        author: "Dan Simmons",
        description: "Epic space opera following pilgrims to the Time Tombs of Hyperion.",
        price: 499,
        category: "Science Fiction",
        genre: "Space Opera",
        stock: 50,
        isbn: "9780553283686",
        pages: 482,
        language: "English",
        publishedDate: "1989-05-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553283686-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553283686-L.jpg"
    },
    {
        title: "The Forever War",
        author: "Joe Haldeman",
        description: "Military science fiction exploring time dilation and the futility of war.",
        price: 425,
        category: "Science Fiction",
        genre: "Military Sci-Fi",
        stock: 55,
        isbn: "9780312536633",
        pages: 236,
        language: "English",
        publishedDate: "1974-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780312536633-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780312536633-L.jpg"
    },
    {
        title: "Solaris",
        author: "Stanislaw Lem",
        description: "A psychological drama about contact with an alien ocean.",
        price: 379,
        category: "Science Fiction",
        genre: "Soft Sci-Fi",
        stock: 45,
        isbn: "9780156027601",
        pages: 214,
        language: "English",
        publishedDate: "1961-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780156027601-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780156027601-L.jpg"
    },
    {
        title: "Kindred",
        author: "Octavia E. Butler",
        description: "A young Black woman is transported through time to a plantation in Maryland.",
        price: 449,
        category: "Science Fiction",
        genre: "Time Travel",
        stock: 75,
        isbn: "9780807083697",
        pages: 264,
        language: "English",
        publishedDate: "1979-06-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780807083697-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780807083697-L.jpg",
        bestseller: true
    },
    {
        title: "Watchmen",
        author: "Alan Moore",
        description: "The seminal graphic novel deconstructing the superhero genre in a dystopian world.",
        price: 799,
        category: "Science Fiction",
        genre: "Graphic Novel",
        stock: 60,
        isbn: "9781779501127",
        pages: 416,
        language: "English",
        publishedDate: "1986-09-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781779501127-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781779501127-L.jpg",
        bestseller: true
    },
    {
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        description: "A chilling vision of a patriarchal, totalitarian state in the former US.",
        price: 399,
        category: "Science Fiction",
        genre: "Dystopian",
        stock: 90,
        isbn: "9780385490818",
        pages: 311,
        language: "English",
        publishedDate: "1985-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
        bestseller: true
    },
    {
        title: "I, Robot",
        author: "Isaac Asimov",
        description: "Interconnected stories exploring the ethics of robotics and the three laws.",
        price: 349,
        category: "Science Fiction",
        genre: "Classic Sci-Fi",
        stock: 85,
        isbn: "9780553382563",
        pages: 224,
        language: "English",
        publishedDate: "1950-12-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553382563-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553382563-L.jpg"
    },
    {
        title: "Children of Time",
        author: "Adrian Tchaikovsky",
        description: "A sweeping saga about humanity's last survivors and a world of evolved spiders.",
        price: 525,
        category: "Science Fiction",
        genre: "Epic Sci-Fi",
        stock: 50,
        isbn: "9781561444318",
        pages: 600,
        language: "English",
        publishedDate: "2015-06-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316452502-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316452502-L.jpg",
        featured: true
    },
    {
        title: "Old Man's War",
        author: "John Scalzi",
        description: "Retired citizens join the colonial defense forces to fight in interstellar wars.",
        price: 399,
        category: "Science Fiction",
        genre: "Military Sci-Fi",
        stock: 65,
        isbn: "9780765348272",
        pages: 320,
        language: "English",
        publishedDate: "2005-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780765348272-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780765348272-L.jpg"
    },
    {
        title: "The Time Machine",
        author: "H.G. Wells",
        description: "The classic tale of the Time Traveller visiting the distant future.",
        price: 199,
        category: "Science Fiction",
        genre: "Classic Sci-Fi",
        stock: 100,
        isbn: "9780141439976",
        pages: 128,
        language: "English",
        publishedDate: "1895-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780141439976-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780141439976-L.jpg"
    }
];

const seedSciFi = async () => {
    try {
        console.log('Seeding 40 Science Fiction books...');
        await Book.insertMany(sciFiBooks);
        console.log('Successfully seeded 40 sci-fi books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding sci-fi books:', error);
        process.exit(1);
    }
};

seedSciFi();
