import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';
import User from './models/User.js';
import bcrypt from 'bcryptjs';

dotenv.config();
connectDB();

const books = [
    {
        title: "The Midnight Library",
        title_ta: "தி மிட்நைட் லைப்ரரி",
        author: "Matt Haig",
        author_ta: "மாட் ஹேக்",
        description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
        price: 499,
        originalPrice: 699,
        category: "Fiction",
        genre: "Contemporary Fiction",
        stock: 45,
        rating: 4.5,
        reviewCount: 2847,
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
        publishedDate: "2020-08-13",
        isbn: "978-0525559474",
        pages: 304,
        language: "English",
        featured: true,
        bestseller: true,
    },
    {
        title: "Atomic Habits",
        title_ta: "அணு பழக்கங்கள்",
        author: "James Clear",
        author_ta: "ஜேம்ஸ் கிளியர்",
        description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. Learn how tiny changes in behavior will add up to remarkable results.",
        price: 399,
        originalPrice: 599,
        category: "Self-Help",
        genre: "Personal Development",
        stock: 120,
        rating: 4.8,
        reviewCount: 5621,
        coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
        publishedDate: "2018-10-16",
        isbn: "978-0735211292",
        pages: 320,
        language: "English",
        featured: true,
        bestseller: true,
    },
    {
        title: "The Silent Patient",
        title_ta: "தி சைலண்ட் பேஷண்ட்",
        author: "Alex Michaelides",
        author_ta: "அலெக்ஸ் மைக்கேலைட்ஸ்",
        description: "Alicia Berenson's life is seemingly perfect. Until one evening, her husband Gabriel returns home late from work, and Alicia shoots him five times in the face.",
        description_ta: "அலிசியா பெரென்சனின் வாழ்க்கை பார்ப்பதற்கு கச்சிதமாக உள்ளது. ஒரு மாலை வரை, அவளுடைய கணவன் கேப்ரியல் வேலையிலிருந்து தாமதமாக வீட்டுக்குத் திரும்புகிறான், அலிசியா அவன் முகத்தில் ஐந்து முறை சுடுகிறாள்.",
        price: 349,
        originalPrice: 499,
        category: "Mystery",
        category_ta: "மர்மம்",
        genre: "Psychological Thriller",
        stock: 67,
        rating: 4.3,
        reviewCount: 3892,
        coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop",
        publishedDate: "2019-02-05",
        isbn: "978-1250301697",
        pages: 336,
        language: "English",
        featured: true,
    },
    {
        title: "Wings of Fire",
        title_ta: "அக்னி சிறகுகள்",
        author: "APJ Abdul Kalam",
        author_ta: "ஏ.பி.ஜே அப்துல் கலாம்",
        description: "An autobiography of one of India's most distinguished scientists and the man who led India's missile program. A story of determination and courage.",
        price: 299,
        category: "Biography",
        genre: "Autobiography",
        stock: 89,
        rating: 4.6,
        reviewCount: 4521,
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
        publishedDate: "1999-01-01",
        isbn: "978-8173711466",
        pages: 180,
        language: "English",
        bestseller: true,
    },
    {
        title: "The Alchemist",
        title_ta: "தி அல்கெமிஸ்ட்",
        author: "Paulo Coelho",
        author_ta: "பாலோ கோயல்ஹோ",
        description: "A magical fable about following your dream, this international bestseller has inspired millions of readers around the world.",
        price: 299,
        originalPrice: 399,
        category: "Fiction",
        genre: "Philosophical Fiction",
        stock: 156,
        rating: 4.7,
        reviewCount: 8934,
        coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop",
        publishedDate: "1988-01-01",
        isbn: "978-0062315007",
        pages: 208,
        language: "English",
        bestseller: true,
    },
    {
        title: "Five Point Someone",
        title_ta: "ஃபைவ் பாயிண்ட் சம்வன்",
        author: "Chetan Bhagat",
        author_ta: "சேத்தன் பகத்",
        description: "What not to do at IIT. The story of three friends whose lives change forever in the hallowed corridors of India's premier engineering institute.",
        description_ta: "ஐஐடியில் என்ன செய்யக்கூடாது. இந்தியாவின் முதன்மையான பொறியியல் நிறுவனத்தின் புனிதமான தாழ்வாரங்களில் மூன்று நண்பர்களின் வாழ்க்கை எப்போதும் மாறுகிறது.",
        price: 199,
        category: "Fiction",
        category_ta: "கற்பனை கதை",
        genre: "Contemporary Fiction",
        stock: 234,
        rating: 4.2,
        reviewCount: 6723,
        coverImage: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop",
        publishedDate: "2004-01-01",
        isbn: "978-8129135476",
        pages: 288,
        language: "English",
    },
    {
        title: "Sapiens",
        title_ta: "சேபியன்ஸ்",
        author: "Yuval Noah Harari",
        author_ta: "யுவால் நோவா ஹராரி",
        description: "A brief history of humankind. How did our species succeed in the battle for dominance? Why did our ancestors come together to create cities and kingdoms?",
        description_ta: "மனிதகுலத்தின் சுருக்கமான வரலாறு. ஆதிக்கத்துக்கான போரில் நமது இனம் எவ்வாறு வெற்றி பெற்றது? நகரங்களையும் ராஜ்ஜியங்களையும் உருவாக்க நம் முன்னோர்கள் ஏன் ஒன்று கூடினார்கள்?",
        price: 599,
        originalPrice: 799,
        category: "Non-Fiction",
        category_ta: "அபுனைவு",
        genre: "History",
        stock: 78,
        rating: 4.6,
        reviewCount: 7234,
        coverImage: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&h=600&fit=crop",
        publishedDate: "2011-01-01",
        isbn: "978-0062316097",
        pages: 464,
        language: "English",
        featured: true,
    },
    {
        title: "It Ends with Us",
        title_ta: "இட் என்ட்ஸ் வித் அஸ்",
        author: "Colleen Hoover",
        author_ta: "கொலின் ஹூவர்",
        description: "A brave and heartbreaking novel that digs its claws into you and doesn't let go, long after you've finished it.",
        description_ta: "ஒரு துணிச்சலான மற்றும் நெஞ்சைப் பிளக்கும் நாவல், நீங்கள் படித்து முடித்த பிறகும் உங்களை விட்டு நீங்காது.",
        price: 349,
        originalPrice: 449,
        category: "Romance",
        category_ta: "காதல்",
        genre: "Contemporary Romance",
        stock: 92,
        rating: 4.4,
        reviewCount: 5123,
        coverImage: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop",
        publishedDate: "2016-08-02",
        isbn: "978-1501110368",
        pages: 384,
        language: "English",
        bestseller: true,
    },
    {
        title: "Project Hail Mary",
        title_ta: "திட்டம் ஹெயில் மேரி",
        author: "Andy Weir",
        author_ta: "ஆண்டி வீர்",
        description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.",
        description_ta: "ரைலேண்ட் கிரேஸ் ஒரு அவநம்பிக்கையான, கடைசி வாய்ப்பு பணியில் தப்பிய ஒரே நபர் - அவர் தோல்வியுற்றால், மனிதகுலமும் பூமியும் அழிந்துவிடும்.",
        price: 449,
        originalPrice: 599,
        category: "Science Fiction",
        category_ta: "அறிவியல் புனைகதை",
        genre: "Hard Science Fiction",
        stock: 56,
        rating: 4.8,
        reviewCount: 3456,
        coverImage: "https://images.unsplash.com/photo-1614544048536-0d28caf77f41?w=400&h=600&fit=crop",
        publishedDate: "2021-05-04",
        isbn: "978-0593135204",
        pages: 496,
        language: "English",
        featured: true,
    },
    {
        title: "The Psychology of Money",
        title_ta: "பணத்தின் உளவியல்",
        author: "Morgan Housel",
        author_ta: "மோர்கன் ஹவுசல்",
        description: "Timeless lessons on wealth, greed, and happiness doing well with money isn't necessarily about what you know. It's about how you behave.",
        description_ta: "செல்வம், பேராசை மற்றும் மகிழ்ச்சி பற்றிய காலமற்ற பாடங்கள் பணத்துடன் சிறப்பாகச் செயல்படுவது என்பது உங்களுக்குத் தெரிந்ததைப் பற்றியது அல்ல. இது நீங்கள் எப்படி நடந்து கொள்கிறீர்கள் என்பது பற்றியது.",
        price: 349,
        category: "Self-Help",
        category_ta: "சுய உதவி",
        genre: "Personal Finance",
        stock: 145,
        rating: 4.7,
        reviewCount: 4892,
        coverImage: "https://images.unsplash.com/photo-1554774853-aae0a22c8aa4?w=400&h=600&fit=crop",
        publishedDate: "2020-09-08",
        isbn: "978-0857197689",
        pages: 256,
        language: "English",
        bestseller: true,
    },
    {
        title: "The Great Gatsby",
        title_ta: "தி கிரேட் கேட்ஸ்பி",
        author: "F. Scott Fitzgerald",
        author_ta: "எஃப். ஸ்காட் ஃபிட்ஸ்ஜெரால்ட்",
        description: "A portrait of the Jazz Age in all of its decadence and excess, this is the quintessential novel of the Roaring Twenties.",
        description_ta: "ஜாஸ் யுகத்தின் வீழ்ச்சி மற்றும் அதிகப்படியான அனைத்து உருவப்படங்களையும் கொண்ட இது, கர்ஜிக்கும் இருபதுகளின் மிகச்சிறந்த நாவலாகும்.",
        price: 199,
        category: "Fiction",
        category_ta: "கற்பனை கதை",
        genre: "Classic Literature",
        stock: 178,
        rating: 4.4,
        reviewCount: 9234,
        coverImage: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop",
        publishedDate: "1925-04-10",
        isbn: "978-0743273565",
        pages: 180,
        language: "English",
    },
    {
        title: "Harry Potter and the Sorcerer's Stone",
        title_ta: "ஹாரி பாட்டர் மற்றும் தத்துவக்கல்",
        author: "J.K. Rowling",
        author_ta: "ஜே.கே. ரவுலிங்",
        description: "Harry Potter has no idea how famous he is. The first book in the beloved Harry Potter series.",
        description_ta: "ஹாரி பாட்டருக்கு தான் எவ்வளவு பிரபலம் என்று தெரியவில்லை. அன்பான ஹாரி பாட்டர் தொடரின் முதல் புத்தகம்.",
        price: 399,
        category: "Children's",
        category_ta: "குழந்தைகள்",
        genre: "Fantasy",
        stock: 234,
        rating: 4.9,
        reviewCount: 12456,
        coverImage: "https://images.unsplash.com/photo-1618666012174-83b441c0bc76?w=400&h=600&fit=crop",
        publishedDate: "1997-06-26",
        isbn: "978-0590353427",
        pages: 309,
        language: "English",
        bestseller: true,
    },
    {
        title: "Thinking, Fast and Slow",
        title_ta: "வேகமாகவும் மற்றும் மெதுவாகவும் சிந்தித்தல்",
        author: "Daniel Kahneman",
        author_ta: "டேனியல் கான்மேன்",
        description: "The organizing principle in this book is a dichotomy between two modes of thought: 'System 1' is fast, instinctive and emotional; 'System 2' is slower, more deliberative, and more logical.",
        description_ta: "இந்த புத்தகத்தில் தி இரண்டு சிந்தனை முறைகளுக்கு இடையிலான ஒரு வகைப்பாடு: 'System 1' வேகமானது, உள்ளுணர்வு மற்றும் உணர்ச்சிவசப்படுவது; 'System 2' மெதுவானது, அதிக ஆலோசனை மற்றும் அதிக தர்க்கரீதியானது.",
        price: 499,
        originalPrice: 699,
        category: "Non-Fiction",
        category_ta: "அபுனைவு",
        genre: "Psychology",
        stock: 85,
        rating: 4.6,
        reviewCount: 12543,
        coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
        publishedDate: "2011-10-25",
        isbn: "978-0374275631",
        pages: 499,
        language: "English",
        featured: true,
    },
    {
        title: "Educated",
        title_ta: "எஜூகேட்டட்",
        author: "Tara Westover",
        author_ta: "தாரா வெஸ்டோவர்",
        description: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom.",
        description_ta: "ஐடஹோ மலைகளில் பிறந்த தாரா வெஸ்டோவர், வகுப்பறையில் முதன்முதலில் அடியெடுத்து வைக்கும் போது அவருக்கு வயது பதினேழு.",
        price: 399,
        category: "Non-Fiction",
        category_ta: "அபுனைவு",
        genre: "Memoir",
        stock: 110,
        rating: 4.7,
        reviewCount: 9876,
        coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop",
        publishedDate: "2018-02-18",
        isbn: "978-0399590504",
        pages: 334,
        language: "English",
    },
    {
        title: "The Subtle Art of Not Giving a F*ck",
        title_ta: "கவலைபடாமல் இருப்பதற்கான நுட்பமான கலை",
        author: "Mark Manson",
        author_ta: "மார்க் மான்சன்",
        description: "A counterintuitive approach to living a good life. Manson advises us to get to know our limitations and accept them.",
        description_ta: "ஒரு நல்ல வாழ்க்கையை வாழ்வதற்கான எதிர் உள்ளுணர்வு அணுகுமுறை. நமது வரம்புகளை அறிந்து அவற்றை ஏற்று கொள்ள மான்சன் நமக்கு அறிவுறுத்துகிறார்.",
        price: 299,
        originalPrice: 499,
        category: "Self-Help",
        category_ta: "சுய உதவி",
        genre: "Personal Development",
        stock: 200,
        rating: 4.4,
        reviewCount: 15678,
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
        publishedDate: "2016-09-13",
        isbn: "978-0062457714",
        pages: 224,
        language: "English",
        bestseller: true,
    },
    {
        title: "Rich Dad Poor Dad",
        title_ta: "ரிச் டாட் புவர் டாட்",
        author: "Robert T. Kiyosaki",
        author_ta: "ராபர்ட் டி. கியோசாகி",
        description: "What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!",
        description_ta: "பணக்காரர்கள் தங்கள் குழந்தைகளுக்கு பணத்தைப் பற்றி என்ன கற்றுக்கொடுக்கிறார்கள், ஏழைகள் மற்றும் நடுத்தர வர்க்கத்தினர் செய்வதில்லை!",
        price: 349,
        category: "Self-Help",
        category_ta: "சுய உதவி",
        genre: "Personal Finance",
        stock: 150,
        rating: 4.6,
        reviewCount: 22345,
        coverImage: "https://images.unsplash.com/photo-1554774853-aae0a22c8aa4?w=400&h=600&fit=crop",
        publishedDate: "1997-04-01",
        isbn: "978-1612680194",
        pages: 336,
        language: "English",
    }
];

import Offer from './models/Offer.js';

const importData = async () => {
    try {
        await Book.deleteMany();
        await User.deleteMany();
        await Offer.deleteMany();

        await Book.insertMany(books);

        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash('123456', salt);


        // Default admin user
        const adminUser = new User({
            name: 'Admin User',
            email: 'admin@example.com',
            password: hashedPassword,
            isAdmin: true,
        });

        // New admin user for Sri Chola Book Shop
        const newAdminPassword = await bcrypt.hash('Admin@2026', salt);
        const sriCholaAdmin = new User({
            name: 'Sri Chola Admin',
            email: 'admin@sricholabooks.com',
            password: newAdminPassword,
            isAdmin: true,
        });

        const regularUser = new User({
            name: 'John Doe',
            email: 'user@example.com',
            password: hashedPassword,
            isAdmin: false,
        });


        await adminUser.save();
        await sriCholaAdmin.save();
        await regularUser.save();

        await Offer.insertMany([
            {
                code: 'WELCOME10',
                discountPercentage: 10,
                expirationDate: new Date('2025-12-31'),
                description: 'Welcome offer: 10% off'
            },
            {
                code: 'BOOKLOVER',
                discountPercentage: 15,
                expirationDate: new Date('2025-12-31'),
                description: 'Special offer for book lovers: 15% off'
            }
        ]);

        console.log('Data Imported!');
        process.exit();
    } catch (error) {
        console.error(`${error}`);
        process.exit(1);
    }
};

importData();
