import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const romanceBooks = [
    {
        title: "Funny Story",
        author: "Emily Henry",
        description: "Daphne and Miles, two people with nothing in common except for their exes, become roommates and start a fake relationship.",
        price: 549,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 50,
        isbn: "9780593441282",
        pages: 400,
        language: "English",
        publishedDate: "2024-04-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593441282-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593441282-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Just for the Summer",
        author: "Abby Jimenez",
        description: "Justin has a curse: every woman he dates finds her soulmate immediately after they break up. Then he meets Emma.",
        price: 499,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 45,
        isbn: "9781538704431",
        pages: 432,
        language: "English",
        publishedDate: "2024-04-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781538704431-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781538704431-L.jpg",
        bestseller: true
    },
    {
        title: "The Paradise Problem",
        author: "Christina Lauren",
        description: "Anna and Liam, who married for financial aid and haven't seen each other in years, must pretend to be happily married at a tropical wedding.",
        price: 525,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 40,
        isbn: "9781982173432",
        pages: 352,
        language: "English",
        publishedDate: "2024-05-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781982173432-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781982173432-L.jpg"
    },
    {
        title: "Wildfire",
        author: "Hannah Grace",
        description: "Two summer camp counselors attempt to maintain a professional relationship after a one-night stand.",
        price: 449,
        category: "Romance",
        genre: "New Adult Romance",
        stock: 60,
        isbn: "9781668026274",
        pages: 400,
        language: "English",
        publishedDate: "2023-10-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781668026274-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781668026274-L.jpg",
        bestseller: true
    },
    {
        title: "The Seven Year Slip",
        author: "Ashley Poston",
        description: "A magical apartment that travels through time leads to a romance between a woman and a man from seven years in the past.",
        price: 499,
        category: "Romance",
        genre: "Magical Realism Romance",
        stock: 35,
        isbn: "9780593336496",
        pages: 352,
        language: "English",
        publishedDate: "2023-06-27",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593336496-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593336496-L.jpg"
    },
    {
        title: "Bride",
        author: "Ali Hazelwood",
        description: "A vampire and a werewolf must navigate an arranged marriage in a world where their kinds are enemies.",
        price: 549,
        category: "Romance",
        genre: "Paranormal Romance",
        stock: 55,
        isbn: "9780593550403",
        pages: 416,
        language: "English",
        publishedDate: "2024-02-06",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593550403-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593550403-L.jpg",
        featured: true
    },
    {
        title: "The Love Hypothesis",
        author: "Ali Hazelwood",
        description: "A PhD candidate enters into a fake relationship with a young professor to convince her friend she's moved on.",
        price: 399,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 100,
        isbn: "9780593336823",
        pages: 384,
        language: "English",
        publishedDate: "2021-09-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593336823-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593336823-L.jpg",
        bestseller: true
    },
    {
        title: "It Ends with Us",
        author: "Colleen Hoover",
        description: "A powerful story about love, loss, and the strength it takes to break a cycle of abuse.",
        price: 425,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 150,
        isbn: "9781501110366",
        pages: 384,
        language: "English",
        publishedDate: "2016-08-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501110366-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501110366-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "The Hating Game",
        author: "Sally Thorne",
        description: "Lucy and Joshua, rivals at a publishing house, find the line between hate and love becoming increasingly blurred.",
        price: 379,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 70,
        isbn: "9780062439598",
        pages: 384,
        language: "English",
        publishedDate: "2016-08-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062439598-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062439598-L.jpg"
    },
    {
        title: "Red, White & Royal Blue",
        author: "Casey McQuiston",
        description: "The son of the US President and the Prince of Wales must fake a friendship that turns into something more.",
        price: 449,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 110,
        isbn: "9781250316776",
        pages: 432,
        language: "English",
        publishedDate: "2019-05-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250316776-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250316776-L.jpg",
        bestseller: true
    },
    {
        title: "People We Meet on Vacation",
        author: "Emily Henry",
        description: "Two best friends who haven't spoken in years take one last vacation together to try and fix their relationship.",
        price: 399,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 90,
        isbn: "9781984806758",
        pages: 384,
        language: "English",
        publishedDate: "2021-05-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781984806758-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781984806758-L.jpg",
        bestseller: true
    },
    {
        title: "The Unhoneymooners",
        author: "Christina Lauren",
        description: "Olive and Ethan, who hate each other, end up on a free honeymoon trip intended for their siblings.",
        price: 349,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 80,
        isbn: "9781501128035",
        pages: 400,
        language: "English",
        publishedDate: "2019-05-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501128035-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501128035-L.jpg"
    },
    {
        title: "Beach Read",
        author: "Emily Henry",
        description: "Two writers with writer's block spend the summer in neighboring beach houses, challenging each other to write in the other's genre.",
        price: 425,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 95,
        isbn: "9781984806734",
        pages: 384,
        language: "English",
        publishedDate: "2020-05-19",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781984806734-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781984806734-L.jpg",
        bestseller: true
    },
    {
        title: "Bridgerton: The Duke and I",
        author: "Julia Quinn",
        description: "The first book in the Bridgerton series, following Daphne Bridgerton and the Duke of Hastings.",
        price: 399,
        category: "Romance",
        genre: "Historical Romance",
        stock: 120,
        isbn: "9780062353597",
        pages: 464,
        language: "English",
        publishedDate: "2000-01-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062353597-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062353597-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "The Kiss Quotient",
        author: "Helen Hoang",
        description: "A woman with Asperger's hires an escort to teach her about intimacy and dating.",
        price: 349,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 75,
        isbn: "9780451490803",
        pages: 336,
        language: "English",
        publishedDate: "2018-06-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780451490803-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780451490803-L.jpg"
    },
    {
        title: "A Curse for True Love",
        author: "Stephanie Garber",
        description: "The conclusion to the Once Upon a Broken Heart trilogy, filled with magic and romance.",
        price: 549,
        category: "Romance",
        genre: "Fantasy Romance",
        stock: 50,
        isbn: "9781250905475",
        pages: 400,
        language: "English",
        publishedDate: "2023-10-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250905475-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250905475-L.jpg"
    },
    {
        title: "Outlander",
        author: "Diana Gabaldon",
        description: "Claire Randall is transported back in time to 18th century Scotland, where she meets Jamie Fraser.",
        price: 499,
        category: "Romance",
        genre: "Historical Romance",
        stock: 100,
        isbn: "9780440212560",
        pages: 850,
        language: "English",
        publishedDate: "1991-06-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780440212560-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780440212560-L.jpg",
        bestseller: true
    },
    {
        title: "You, with a View",
        author: "Jessica Joyce",
        description: "A woman discovers a hidden love story from her grandmother's past and goes on a road trip with her high school rival.",
        price: 449,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 45,
        isbn: "9780593638422",
        pages: 384,
        language: "English",
        publishedDate: "2023-07-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593638422-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593638422-L.jpg"
    },
    {
        title: "Happy Place",
        author: "Emily Henry",
        description: "A couple who broke up months ago pretend to still be together during their annual friendship group vacation.",
        price: 529,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 85,
        isbn: "9781984806710",
        pages: 400,
        language: "English",
        publishedDate: "2023-04-25",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781984806710-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781984806710-L.jpg",
        bestseller: true
    },
    {
        title: "Business Not As Usual",
        author: "Sharon C. Cooper",
        description: "A career-driven woman and a man who prioritizes family find their paths crossing in unexpected ways.",
        price: 479,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 35,
        isbn: "9780593437505",
        pages: 336,
        language: "English",
        publishedDate: "2022-04-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593437505-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593437505-L.jpg"
    },
    {
        title: "The Heart Principle",
        author: "Helen Hoang",
        description: "A violinist facing burnout and a man who is the complete opposite of what she expected find a connection.",
        price: 425,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 55,
        isbn: "9780451490841",
        pages: 336,
        language: "English",
        publishedDate: "2021-08-31",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780451490841-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780451490841-L.jpg"
    },
    {
        title: "Check & Mate",
        author: "Ali Hazelwood",
        description: "A high-stakes chess world becomes the backdrop for a rivalry-turned-romance.",
        price: 499,
        category: "Romance",
        genre: "Young Adult Romance",
        stock: 65,
        isbn: "9780593619919",
        pages: 352,
        language: "English",
        publishedDate: "2023-11-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593619919-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593619919-L.jpg",
        featured: true
    },
    {
        title: "Final Offer",
        author: "Lauren Asher",
        description: "The conclusion to the Dreamland Billionaires series, following Callahan and Alana.",
        price: 449,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 70,
        isbn: "9781737507741",
        pages: 560,
        language: "English",
        publishedDate: "2023-01-31",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781737507741-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781737507741-L.jpg",
        bestseller: true
    },
    {
        title: "The Rule Book",
        author: "Sarah Adams",
        description: "A sports agent and her ex-boyfriend, a professional football player, must work together.",
        price: 499,
        category: "Romance",
        genre: "Sports Romance",
        stock: 50,
        isbn: "9780593500804",
        pages: 352,
        language: "English",
        publishedDate: "2024-04-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593500804-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593500804-L.jpg"
    },
    {
        title: "A Touch of Chaos",
        author: "Scarlett St. Clair",
        description: "The final book in the Hades x Persephone saga.",
        price: 549,
        category: "Romance",
        genre: "Fantasy Romance",
        stock: 40,
        isbn: "9781728283081",
        pages: 400,
        language: "English",
        publishedDate: "2024-03-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781728283081-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781728283081-L.jpg"
    },
    {
        title: "The Idea of You",
        author: "Robinne Lee",
        description: "A 40-year-old mother begins an unexpected romance with the young lead singer of a world-famous boy band.",
        price: 399,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 60,
        isbn: "9781250125903",
        pages: 384,
        language: "English",
        publishedDate: "2017-06-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250125903-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250125903-L.jpg"
    },
    {
        title: "Verity",
        author: "Colleen Hoover",
        description: "A struggling writer discovers a terrifying unfinished autobiography in the home of a famous author.",
        price: 449,
        category: "Romance",
        genre: "Romantic Thriller",
        stock: 130,
        isbn: "9781538724545",
        pages: 336,
        language: "English",
        publishedDate: "2018-12-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781538724545-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781538724545-L.jpg",
        bestseller: true
    },
    {
        title: "Archer's Voice",
        author: "Mia Sheridan",
        description: "A woman fleeing a traumatic experience finds solace and connection with a man who lives in silence.",
        price: 379,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 55,
        isbn: "9781455554379",
        pages: 352,
        language: "English",
        publishedDate: "2014-01-25",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781455554379-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781455554379-L.jpg"
    },
    {
        title: "The Notebook",
        author: "Nicholas Sparks",
        description: "The enduring love story of Noah and Allie, spanning decades and overcoming all odds.",
        price: 299,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 120,
        isbn: "9780446605236",
        pages: 214,
        language: "English",
        publishedDate: "1996-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780446605236-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780446605236-L.jpg",
        bestseller: true
    },
    {
        title: "Icebreaker",
        author: "Hannah Grace",
        description: "A competitive figure skater and a hockey captain must share a rink.",
        price: 499,
        category: "Romance",
        genre: "Sports Romance",
        stock: 140,
        isbn: "9781668026038",
        pages: 448,
        language: "English",
        publishedDate: "2022-11-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781668026038-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781668026038-L.jpg",
        bestseller: true
    },
    {
        title: "Wait for It",
        author: "Mariana Zapata",
        description: "A slow-burn romance about a woman rebuilding her life and the neighbor she can't ignore.",
        price: 425,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 40,
        isbn: "9781310322303",
        pages: 670,
        language: "English",
        publishedDate: "2016-12-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781310322303-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781310322303-L.jpg"
    },
    {
        title: "Puck Out",
        author: "Ruby Redford",
        description: "A steamy sports romance featuring a bad-boy hockey player.",
        price: 479,
        category: "Romance",
        genre: "Sports Romance",
        stock: 35,
        isbn: "9781648754129",
        pages: 320,
        language: "English",
        publishedDate: "2023-09-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781648754129-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781648754129-L.jpg"
    },
    {
        title: "Not in Love",
        author: "Ali Hazelwood",
        description: "A new academic romance from the queen of the genre.",
        price: 549,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 50,
        isbn: "9780593437345",
        pages: 416,
        language: "English",
        publishedDate: "2024-06-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593437345-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593437345-L.jpg",
        featured: true
    },
    {
        title: "The Spellseller",
        author: "Leanne Cooper",
        description: "A magical romance set in a world where spells are bought and sold.",
        price: 525,
        category: "Romance",
        genre: "Fantasy Romance",
        stock: 30,
        isbn: "9781639105470",
        pages: 352,
        language: "English",
        publishedDate: "2024-02-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781639105470-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781639105470-L.jpg"
    },
    {
        title: "Whisky Business",
        author: "Maggie McGinnis",
        description: "A delightful romantic comedy set in a Scottish distillery.",
        price: 449,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 45,
        isbn: "9781682815473",
        pages: 320,
        language: "English",
        publishedDate: "2024-01-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781682815473-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781682815473-L.jpg"
    },
    {
        title: "A Lady's Guide to Scandal",
        author: "Sophie Irwin",
        description: "A witty Regency romance about a widow who inherits a fortune and a reputation.",
        price: 499,
        category: "Romance",
        genre: "Historical Romance",
        stock: 50,
        isbn: "9780593439059",
        pages: 352,
        language: "English",
        publishedDate: "2023-07-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593439059-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593439059-L.jpg"
    },
    {
        title: "The Fiancée Farce",
        author: "Alexandria Bellefleur",
        description: "A delightful queer romance about a fake engagement.",
        price: 479,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 40,
        isbn: "9780063258495",
        pages: 384,
        language: "English",
        publishedDate: "2023-04-18",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780063258495-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780063258495-L.jpg"
    },
    {
        title: "Business Casual",
        author: "B.K. Borison",
        description: "A sweet romance set in a small town.",
        price: 425,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 35,
        isbn: "9780593717547",
        pages: 352,
        language: "English",
        publishedDate: "2024-06-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593717547-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593717547-L.jpg"
    },
    {
        title: "Love, Redesigned",
        author: "Lauren Asher",
        description: "The first book in the Lakefront Billionaires series.",
        price: 549,
        category: "Romance",
        genre: "Contemporary Romance",
        stock: 65,
        isbn: "9781737507758",
        pages: 450,
        language: "English",
        publishedDate: "2023-11-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781737507758-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781737507758-L.jpg",
        featured: true
    },
    {
        title: "The Guest",
        author: "Emma Cline",
        description: "A summer of deception and desire on the North Fork of Long Island.",
        price: 599,
        category: "Romance",
        genre: "Literary Fiction",
        stock: 40,
        isbn: "9780812998627",
        pages: 304,
        language: "English",
        publishedDate: "2023-05-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780812998627-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780812998627-L.jpg"
    }
];

const seedRomance = async () => {
    try {
        console.log('Seeding 40 Romance books...');
        await Book.insertMany(romanceBooks);
        console.log('Successfully seeded 40 romance books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding romance books:', error);
        process.exit(1);
    }
};

seedRomance();
