import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const childrenBooks = [
    {
        title: "The Very Hungry Caterpillar",
        author: "Eric Carle",
        description: "A classic picture book following the journey of a tiny caterpillar who eats his way through a variety of foods.",
        price: 299,
        category: "Children's",
        genre: "Picture Book",
        stock: 100,
        isbn: "9780399226908",
        pages: 32,
        language: "English",
        publishedDate: "1969-06-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780399226908-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780399226908-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Where the Wild Things Are",
        author: "Maurice Sendak",
        description: "Max's imaginative journey to an island inhabited by 'Wild Things' after being sent to bed without supper.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 80,
        isbn: "9780060254926",
        pages: 48,
        language: "English",
        publishedDate: "1963-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060254926-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060254926-L.jpg",
        bestseller: true
    },
    {
        title: "Goodnight Moon",
        author: "Margaret Wise Brown",
        description: "A beloved bedtime story that follows a little bunny saying goodnight to everything in his room.",
        price: 249,
        category: "Children's",
        genre: "Bedtime Story",
        stock: 120,
        isbn: "9780060775858",
        pages: 32,
        language: "English",
        publishedDate: "1947-09-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060775858-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060775858-L.jpg",
        bestseller: true
    },
    {
        title: "The Gruffalo",
        author: "Julia Donaldson",
        description: "A mouse takes a stroll through the deep dark wood and invents a terrifying creature to scare off predators.",
        price: 399,
        category: "Children's",
        genre: "Picture Book",
        stock: 90,
        isbn: "9780333710937",
        pages: 32,
        language: "English",
        publishedDate: "1999-03-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780333710937-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780333710937-L.jpg",
        featured: true
    },
    {
        title: "Charlotte's Web",
        author: "E.B. White",
        description: "The story of a pig named Wilbur and his friendship with a barn spider named Charlotte.",
        price: 325,
        category: "Children's",
        genre: "Classic Fiction",
        stock: 70,
        isbn: "9780064400558",
        pages: 192,
        language: "English",
        publishedDate: "1952-10-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg",
        bestseller: true
    },
    {
        title: "The Cat in the Hat",
        author: "Dr. Seuss",
        description: "A mischievous cat visits two children on a rainy day, turning their house upside down.",
        price: 299,
        category: "Children's",
        genre: "Beginning Reader",
        stock: 110,
        isbn: "9780394800011",
        pages: 61,
        language: "English",
        publishedDate: "1957-03-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780394800011-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780394800011-L.jpg",
        bestseller: true
    },
    {
        title: "Green Eggs and Ham",
        author: "Dr. Seuss",
        description: "Sam-I-Am tries to convince a grumpy character to try a dish of green eggs and ham.",
        price: 299,
        category: "Children's",
        genre: "Beginning Reader",
        stock: 100,
        isbn: "9780394800165",
        pages: 62,
        language: "English",
        publishedDate: "1960-08-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780394800165-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780394800165-L.jpg",
        bestseller: true
    },
    {
        title: "The Lion, the Witch and the Wardrobe",
        author: "C.S. Lewis",
        description: "Four siblings discover a magical world inside a wardrobe, leading to an epic battle between good and evil.",
        price: 399,
        category: "Children's",
        genre: "Fantasy",
        stock: 85,
        isbn: "9780064471046",
        pages: 208,
        language: "English",
        publishedDate: "1950-10-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780064471046-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780064471046-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Matilda",
        author: "Roald Dahl",
        description: "A brilliant young girl with telekinetic powers takes on her mean parents and an even meaner headmistress.",
        price: 349,
        category: "Children's",
        genre: "Contemporary Fiction",
        stock: 75,
        isbn: "9780142410370",
        pages: 240,
        language: "English",
        publishedDate: "1988-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg",
        bestseller: true
    },
    {
        title: "Charlie and the Chocolate Factory",
        author: "Roald Dahl",
        description: "Five lucky children win golden tickets for a tour of Willy Wonka's mysterious chocolate factory.",
        price: 349,
        category: "Children's",
        genre: "Fantasy",
        stock: 80,
        isbn: "9780142410318",
        pages: 176,
        language: "English",
        publishedDate: "1964-01-17",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780142410318-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780142410318-L.jpg",
        bestseller: true
    },
    {
        title: "A Wrinkle in Time",
        author: "Madeleine L'Engle",
        description: "Meg Murry and her brother go on a cosmic journey to rescue their father from a dark force.",
        price: 399,
        category: "Children's",
        genre: "Science Fantasy",
        stock: 65,
        isbn: "9780312367541",
        pages: 256,
        language: "English",
        publishedDate: "1962-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780312367541-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780312367541-L.jpg"
    },
    {
        title: "The Tale of Peter Rabbit",
        author: "Beatrix Potter",
        description: "The mischievous Peter Rabbit defies his mother's warnings and enters Mr. McGregor's garden.",
        price: 199,
        category: "Children's",
        genre: "Animal Story",
        stock: 150,
        isbn: "9780723247708",
        pages: 70,
        language: "English",
        publishedDate: "1902-12-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780723247708-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780723247708-L.jpg"
    },
    {
        title: "Winnie-the-Pooh",
        author: "A.A. Milne",
        description: "The adventures of a honey-loving bear and his friends in the Hundred Acre Wood.",
        price: 349,
        category: "Children's",
        genre: "Animal Story",
        stock: 90,
        isbn: "9780140361216",
        pages: 161,
        language: "English",
        publishedDate: "1926-10-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780140361216-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780140361216-L.jpg",
        bestseller: true
    },
    {
        title: "Alice's Adventures in Wonderland",
        author: "Lewis Carroll",
        description: "Alice falls down a rabbit hole into a nonsensical world inhabited by strange creatures.",
        price: 249,
        category: "Children's",
        genre: "Fantasy",
        stock: 100,
        isbn: "9780141439761",
        pages: 192,
        language: "English",
        publishedDate: "1865-11-26",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg"
    },
    {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        description: "Bilbo Baggins, a home-loving hobbit, is swept into an epic quest to reclaim a stolen treasure.",
        price: 499,
        category: "Children's",
        genre: "Fantasy Adventure",
        stock: 110,
        isbn: "9780618260300",
        pages: 310,
        language: "English",
        publishedDate: "1937-09-21",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780618260300-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780618260300-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        description: "A young boy discovers he is a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry.",
        price: 599,
        category: "Children's",
        genre: "Fantasy",
        stock: 200,
        isbn: "9780590353403",
        pages: 309,
        language: "English",
        publishedDate: "1997-06-26",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780590353403-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780590353403-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Don't Let the Pigeon Drive the Bus!",
        author: "Mo Willems",
        description: "A persistent pigeon tries every trick in the book to get his claws on the wheel of a bus.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 85,
        isbn: "9780786819881",
        pages: 40,
        language: "English",
        publishedDate: "2003-04-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780786819881-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780786819881-L.jpg",
        bestseller: true
    },
    {
        title: "The Giving Tree",
        author: "Shel Silverstein",
        description: "A poignant story about the lifelong relationship between a boy and a selfless apple tree.",
        price: 399,
        category: "Children's",
        genre: "Picture Book",
        stock: 95,
        isbn: "9780060256654",
        pages: 64,
        language: "English",
        publishedDate: "1964-10-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060256654-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060256654-L.jpg",
        bestseller: true
    },
    {
        title: "Oh, the Places You'll Go!",
        author: "Dr. Seuss",
        description: "An inspirational message for anyone starting a new journey or facing new challenges.",
        price: 449,
        category: "Children's",
        genre: "Inspirational",
        stock: 110,
        isbn: "9780679805274",
        pages: 56,
        language: "English",
        publishedDate: "1990-01-22",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780679805274-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780679805274-L.jpg",
        bestseller: true
    },
    {
        title: "Lyle, Lyle, Crocodile",
        author: "Bernard Waber",
        description: "A helpful and friendly crocodile living in a big city must win over a skeptical neighbor.",
        price: 299,
        category: "Children's",
        genre: "Picture Book",
        stock: 60,
        isbn: "9780395137246",
        pages: 48,
        language: "English",
        publishedDate: "1965-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780395137246-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780395137246-L.jpg"
    },
    {
        title: "Harold and the Purple Crayon",
        author: "Crockett Johnson",
        description: "A small boy uses his purple crayon to create an adventurous world of his own.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 75,
        isbn: "9780064430227",
        pages: 64,
        language: "English",
        publishedDate: "1955-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780064430227-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780064430227-L.jpg"
    },
    {
        title: "The Snowy Day",
        author: "Ezra Jack Keats",
        description: "A beautiful exploration of a young boy's wonder and joy on a snowy day.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 80,
        isbn: "9780140501827",
        pages: 40,
        language: "English",
        publishedDate: "1962-11-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780140501827-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780140501827-L.jpg",
        bestseller: true
    },
    {
        title: "Pat the Bunny",
        author: "Dorothy Kunhardt",
        description: "A classic touch-and-feel book for the youngest of readers.",
        price: 199,
        category: "Children's",
        genre: "Tactile Book",
        stock: 120,
        isbn: "9780307120007",
        pages: 18,
        language: "English",
        publishedDate: "1940-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780307120007-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780307120007-L.jpg"
    },
    {
        title: "Stellaluna",
        author: "Janell Cannon",
        description: "A baby fruit bat is separated from her mother and raised by a family of birds.",
        price: 399,
        category: "Children's",
        genre: "Animal Story",
        stock: 65,
        isbn: "9780152802172",
        pages: 48,
        language: "English",
        publishedDate: "1993-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780152802172-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780152802172-L.jpg"
    },
    {
        title: "No, David!",
        author: "David Shannon",
        description: "A funny and relatable story about a mischievous boy named David.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 90,
        isbn: "9780439129657",
        pages: 32,
        language: "English",
        publishedDate: "1998-09-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780439129657-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780439129657-L.jpg",
        bestseller: true
    },
    {
        title: "Click, Clack, Moo: Cows That Type",
        author: "Doreen Cronin",
        description: "Chaos ensues on the farm when the cows find an old typewriter and start making demands.",
        price: 349,
        category: "Children's",
        genre: "Humor",
        stock: 75,
        isbn: "9780689832130",
        pages: 32,
        language: "English",
        publishedDate: "2000-02-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780689832130-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780689832130-L.jpg"
    },
    {
        title: "If You Give a Mouse a Cookie",
        author: "Laura Numeroff",
        description: "A funny chain reaction begins when a boy shares a cookie with a visiting mouse.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 100,
        isbn: "9780060245863",
        pages: 40,
        language: "English",
        publishedDate: "1985-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060245863-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060245863-L.jpg",
        bestseller: true
    },
    {
        title: "The Polar Express",
        author: "Chris Van Allsburg",
        description: "A magical train ride to the North Pole on Christmas Eve.",
        price: 499,
        category: "Children's",
        genre: "Holiday Story",
        stock: 80,
        isbn: "9780395389492",
        pages: 32,
        language: "English",
        publishedDate: "1985-11-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780395389492-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780395389492-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Officer Buckle and Gloria",
        author: "Peggy Rathmann",
        description: "A safety officer's presentations become much more entertaining when his dog, Gloria, helps out.",
        price: 349,
        category: "Children's",
        genre: "Humor",
        stock: 60,
        isbn: "9780399226168",
        pages: 40,
        language: "English",
        publishedDate: "1995-09-21",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780399226168-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780399226168-L.jpg"
    },
    {
        title: "Duck on a Bike",
        author: "David Shannon",
        description: "A brave duck decides to try something new, inspiring his fellow farm animals.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 70,
        isbn: "9780439050234",
        pages: 32,
        language: "English",
        publishedDate: "2002-04-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780439050234-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780439050234-L.jpg"
    },
    {
        title: "Dragons Love Tacos",
        author: "Adam Rubin",
        description: "An essential guide to hosting a taco party for your dragon friends (but stay away from the spicy salsa!).",
        price: 399,
        category: "Children's",
        genre: "Humor",
        stock: 110,
        isbn: "9780803736801",
        pages: 40,
        language: "English",
        publishedDate: "2012-06-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780803736801-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780803736801-L.jpg",
        bestseller: true
    },
    {
        title: "Creepy Carrots!",
        author: "Aaron Reynolds",
        description: "Jasper Rabbit loves carrots, but he thinks they might be following him.",
        price: 349,
        category: "Children's",
        genre: "Humor",
        stock: 55,
        isbn: "9781442402973",
        pages: 40,
        language: "English",
        publishedDate: "2012-08-21",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781442402973-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781442402973-L.jpg"
    },
    {
        title: "The Book with No Pictures",
        author: "B.J. Novak",
        description: "A hilariously clever book that forces the reader to say some very silly things.",
        price: 399,
        category: "Children's",
        genre: "Humor",
        stock: 90,
        isbn: "9780803741713",
        pages: 48,
        language: "English",
        publishedDate: "2014-09-30",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780803741713-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780803741713-L.jpg",
        bestseller: true
    },
    {
        title: "Pete the Cat: I Love My White Shoes",
        author: "Eric Litwin",
        description: "Pete the Cat keeps on singing no matter what he steps in.",
        price: 349,
        category: "Children's",
        genre: "Musical Story",
        stock: 100,
        isbn: "9780061906220",
        pages: 40,
        language: "English",
        publishedDate: "2010-03-02",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780061906220-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780061906220-L.jpg",
        bestseller: true
    },
    {
        title: "The Day the Crayons Quit",
        author: "Drew Daywalt",
        description: "Duncan's crayons have had enough and they've gone on strike.",
        price: 399,
        category: "Children's",
        genre: "Humor",
        stock: 85,
        isbn: "9780399255373",
        pages: 40,
        language: "English",
        publishedDate: "2013-06-27",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780399255373-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780399255373-L.jpg",
        bestseller: true
    },
    {
        title: "Room on the Broom",
        author: "Julia Donaldson",
        description: "A friendly witch invites a variety of animal friends to ride on her broomstick.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 75,
        isbn: "9780333903384",
        pages: 32,
        language: "English",
        publishedDate: "2001-08-31",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780333903384-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780333903384-L.jpg"
    },
    {
        title: "The Snail and the Whale",
        author: "Julia Donaldson",
        description: "An unlikely duo goes on an epic oceanic adventure together.",
        price: 349,
        category: "Children's",
        genre: "Adventure",
        stock: 65,
        isbn: "9780333904404",
        pages: 32,
        language: "English",
        publishedDate: "2003-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780333904404-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780333904404-L.jpg"
    },
    {
        title: "Lost and Found",
        author: "Oliver Jeffers",
        description: "A boy finds a penguin at his door and decides to help it find its way home.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 70,
        isbn: "9780007150366",
        pages: 32,
        language: "English",
        publishedDate: "2005-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780007150366-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780007150366-L.jpg"
    },
    {
        title: "The Dot",
        author: "Peter H. Reynolds",
        description: "A young girl discovers the power of her own creativity starting with a single dot.",
        price: 349,
        category: "Children's",
        genre: "Inspirational",
        stock: 60,
        isbn: "9780763619619",
        pages: 32,
        language: "English",
        publishedDate: "2003-09-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780763619619-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780763619619-L.jpg"
    },
    {
        title: "We're Going on a Bear Hunt",
        author: "Michael Rosen",
        description: "A family sets out on an adventurous quest to find a bear, encountering various obstacles.",
        price: 349,
        category: "Children's",
        genre: "Picture Book",
        stock: 85,
        isbn: "9780689504761",
        pages: 36,
        language: "English",
        publishedDate: "1989-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780689504761-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780689504761-L.jpg",
        bestseller: true
    }
];

const seedChildren = async () => {
    try {
        console.log('Seeding 40 Children\'s books...');
        await Book.insertMany(childrenBooks);
        console.log('Successfully seeded 40 children\'s books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding children\'s books:', error);
        process.exit(1);
    }
};

seedChildren();
