import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const biographyBooks = [
    {
        title: "Steve Jobs",
        author: "Walter Isaacson",
        description: "The exclusive biography of the visionary Apple co-founder, based on more than forty interviews.",
        price: 599,
        category: "Biography",
        genre: "Technology",
        stock: 100,
        isbn: "9781451648539",
        pages: 656,
        language: "English",
        publishedDate: "2011-10-24",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "The Diary of a Young Girl",
        author: "Anne Frank",
        description: "The poignant and powerful diary of a Jewish girl hiding from the Nazis in occupied Amsterdam.",
        price: 299,
        category: "Biography",
        genre: "History",
        stock: 120,
        isbn: "9780553296983",
        pages: 283,
        language: "English",
        publishedDate: "1947-06-25",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
        bestseller: true
    },
    {
        title: "Long Walk to Freedom",
        author: "Nelson Mandela",
        description: "The autobiography of the late South African President and civil rights leader.",
        price: 499,
        category: "Biography",
        genre: "Politics",
        stock: 80,
        isbn: "9780316548182",
        pages: 656,
        language: "English",
        publishedDate: "1994-11-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg"
    },
    {
        title: "Elon Musk",
        author: "Walter Isaacson",
        description: "The definitive biography of the tech entrepreneur who is transforming the space and EV industries.",
        price: 649,
        category: "Biography",
        genre: "Technology",
        stock: 75,
        isbn: "9781982181284",
        pages: 688,
        language: "English",
        publishedDate: "2023-09-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "The Autobiography of Malcolm X",
        author: "Malcolm X and Alex Haley",
        description: "The life story of the influential Black nationalist and human rights activist.",
        price: 399,
        category: "Biography",
        genre: "Politics",
        stock: 70,
        isbn: "9780345350688",
        pages: 528,
        language: "English",
        publishedDate: "1965-10-29",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780345350688-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780345350688-L.jpg",
        bestseller: true
    },
    {
        title: "I Am Malala",
        author: "Malala Yousafzai",
        description: "The story of the girl who stood up for education and was shot by the Taliban.",
        price: 349,
        category: "Biography",
        genre: "Human Rights",
        stock: 90,
        isbn: "9780316322409",
        pages: 320,
        language: "English",
        publishedDate: "2013-10-08",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780316322409-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780316322409-L.jpg",
        bestseller: true
    },
    {
        title: "Shoe Dog",
        author: "Phil Knight",
        description: "A memoir by the creator of Nike, detailing the challenges and triumphs of building a global brand.",
        price: 449,
        category: "Biography",
        genre: "Business",
        stock: 110,
        isbn: "9781501135910",
        pages: 400,
        language: "English",
        publishedDate: "2016-04-26",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Leonardo da Vinci",
        author: "Walter Isaacson",
        description: "An exploration of the life and mind of the ultimate Renaissance man.",
        price: 525,
        category: "Biography",
        genre: "Art",
        stock: 50,
        isbn: "9781501139154",
        pages: 600,
        language: "English",
        publishedDate: "2017-10-17",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501139154-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501139154-L.jpg"
    },
    {
        title: "Greenlights",
        author: "Matthew McConaughey",
        description: "An unconventional memoir filled with stories, wisdom, and life lessons from the Oscar-winning actor.",
        price: 499,
        category: "Biography",
        genre: "Entertainment",
        stock: 130,
        isbn: "9780593139134",
        pages: 304,
        language: "English",
        publishedDate: "2020-10-20",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593139134-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593139134-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Friends, Lovers, and the Big Terrible Thing",
        author: "Matthew Perry",
        description: "The late Friends star's candid and courageous memoir about his life and struggles.",
        price: 549,
        category: "Biography",
        genre: "Entertainment",
        stock: 85,
        isbn: "9781250866448",
        pages: 272,
        language: "English",
        publishedDate: "2022-11-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781250866448-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781250866448-L.jpg",
        bestseller: true
    },
    {
        title: "Wild",
        author: "Cheryl Strayed",
        description: "A woman's journey of self-discovery while hiking the Pacific Crest Trail.",
        price: 399,
        category: "Biography",
        genre: "Adventure",
        stock: 65,
        isbn: "9780307476074",
        pages: 315,
        language: "English",
        publishedDate: "2012-03-20",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780307476074-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780307476074-L.jpg",
        bestseller: true
    },
    {
        title: "Hamilton",
        author: "Ron Chernow",
        description: "The inspiration for the hit Broadway musical, a deep dive into the life of Alexander Hamilton.",
        price: 599,
        category: "Biography",
        genre: "History",
        stock: 60,
        isbn: "9780143034759",
        pages: 818,
        language: "English",
        publishedDate: "2004-03-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780143034759-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780143034759-L.jpg",
        featured: true
    },
    {
        title: "Einstein: His Life and Universe",
        author: "Walter Isaacson",
        description: "The life of the genius who reimagined the universe, based on newly released personal letters.",
        price: 525,
        category: "Biography",
        genre: "Science",
        stock: 45,
        isbn: "9780743264730",
        pages: 704,
        language: "English",
        publishedDate: "2007-04-10",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780743264730-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780743264730-L.jpg"
    },
    {
        title: "Unbroken",
        author: "Laura Hillenbrand",
        description: "A World War II story of survival, resilience, and redemption.",
        price: 449,
        category: "Biography",
        genre: "History",
        stock: 95,
        isbn: "9781400064168",
        pages: 473,
        language: "English",
        publishedDate: "2010-11-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781400064168-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781400064168-L.jpg",
        bestseller: true
    },
    {
        title: "Into the Wild",
        author: "Jon Krakauer",
        description: "The true story of Christopher McCandless and his journey into the Alaskan wilderness.",
        price: 349,
        category: "Biography",
        genre: "Adventure",
        stock: 120,
        isbn: "9780385486804",
        pages: 207,
        language: "English",
        publishedDate: "1996-01-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780385486804-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780385486804-L.jpg",
        bestseller: true
    },
    {
        title: "Finding Me",
        author: "Viola Davis",
        description: "A deeply personal memoir by the Oscar-winning actress about her life and career.",
        price: 499,
        category: "Biography",
        genre: "Entertainment",
        stock: 75,
        isbn: "9780063037328",
        pages: 304,
        language: "English",
        publishedDate: "2022-04-26",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780063037328-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780063037328-L.jpg",
        bestseller: true
    },
    {
        title: "The Glass Castle",
        author: "Jeannette Walls",
        description: "A remarkable memoir of resilience and redemption, and a look at an unconventional family.",
        price: 399,
        category: "Biography",
        genre: "Memoir",
        stock: 100,
        isbn: "9780743247542",
        pages: 288,
        language: "English",
        publishedDate: "2005-03-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780743247542-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780743247542-L.jpg",
        bestseller: true
    },
    {
        title: "Infidel",
        author: "Ayaan Hirsi Ali",
        description: "A powerful memoir of a woman's journey from a strict Muslim upbringing to intellectual freedom.",
        price: 349,
        category: "Biography",
        genre: "Human Rights",
        stock: 50,
        isbn: "9780743289689",
        pages: 353,
        language: "English",
        publishedDate: "2007-02-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780743289689-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780743289689-L.jpg"
    },
    {
        title: "Open",
        author: "Andre Agassi",
        description: "A candid and compelling autobiography by the tennis legend.",
        price: 425,
        category: "Biography",
        genre: "Sports",
        stock: 80,
        isbn: "9780307268198",
        pages: 400,
        language: "English",
        publishedDate: "2009-11-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780307268198-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780307268198-L.jpg",
        bestseller: true
    },
    {
        title: "Just Kids",
        author: "Patti Smith",
        description: "A memoir of the artist's relationship with Robert Mapplethorpe in late 60s/70s New York.",
        price: 399,
        category: "Biography",
        genre: "Art",
        stock: 60,
        isbn: "9780060936228",
        pages: 304,
        language: "English",
        publishedDate: "2010-01-19",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780060936228-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780060936228-L.jpg"
    },
    {
        title: "The Year of Magical Thinking",
        author: "Joan Didion",
        description: "A powerful exploration of grief and loss following the death of the author's husband.",
        price: 349,
        category: "Biography",
        genre: "Memoir",
        stock: 55,
        isbn: "9781400043149",
        pages: 227,
        language: "English",
        publishedDate: "2005-10-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781400043149-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781400043149-L.jpg"
    },
    {
        title: "Crying in H Mart",
        author: "Michelle Zauner",
        description: "A beautiful memoir about grief, identity, and the importance of family and food.",
        price: 449,
        category: "Biography",
        genre: "Memoir",
        stock: 110,
        isbn: "9780525657743",
        pages: 256,
        language: "English",
        publishedDate: "2021-04-20",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780525657743-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780525657743-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Total Recall",
        author: "Arnold Schwarzenegger",
        description: "The incredible true story of the world's most famous bodybuilder, actor, and politician.",
        price: 499,
        category: "Biography",
        genre: "Entertainment",
        stock: 70,
        isbn: "9781849839716",
        pages: 656,
        language: "English",
        publishedDate: "2012-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781849839716-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781849839716-L.jpg"
    },
    {
        title: "Beneath the Tamarind Tree",
        author: "Isha Sesay",
        description: "A powerful account of the Chibok schoolgirls kidnapped by Boko Haram.",
        price: 479,
        category: "Biography",
        genre: "Politics",
        stock: 35,
        isbn: "9780062686671",
        pages: 384,
        language: "English",
        publishedDate: "2019-07-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062686671-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062686671-L.jpg"
    },
    {
        title: "Kitchen Confidential",
        author: "Anthony Bourdain",
        description: "The brutal and honest look into the world of high-pressure kitchens.",
        price: 349,
        category: "Biography",
        genre: "Entertainment",
        stock: 90,
        isbn: "9781582340821",
        pages: 320,
        language: "English",
        publishedDate: "2000-05-22",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781582340821-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781582340821-L.jpg",
        bestseller: true
    },
    {
        title: "The Code Breaker",
        author: "Walter Isaacson",
        description: "The story of Jennifer Doudna and the future of the human race through gene editing.",
        price: 549,
        category: "Biography",
        genre: "Science",
        stock: 80,
        isbn: "9781982115852",
        pages: 536,
        language: "English",
        publishedDate: "2021-03-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781982115852-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781982115852-L.jpg",
        featured: true
    },
    {
        title: "Man's Search for Meaning",
        author: "Viktor Frankl",
        description: "Finding meaning even in the most dire circumstances within concentration camps.",
        price: 299,
        category: "Biography",
        genre: "Philosophy",
        stock: 150,
        isbn: "9780807014295",
        pages: 184,
        language: "English",
        publishedDate: "1946-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
        bestseller: true
    },
    {
        title: "Why Not Me?",
        author: "Mindy Kaling",
        description: "The actress and writer shares her thoughts on life, love, and career in her signature comedic style.",
        price: 349,
        category: "Biography",
        genre: "Entertainment",
        stock: 100,
        isbn: "9780804138147",
        pages: 240,
        language: "English",
        publishedDate: "2015-09-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780804138147-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780804138147-L.jpg"
    },
    {
        title: "I'm Glad My Mom Died",
        author: "Jennette McCurdy",
        description: "The former iCarly star's heartbreaking and hilarious memoir about her life as a child star.",
        price: 525,
        category: "Biography",
        genre: "Entertainment",
        stock: 150,
        isbn: "9781982185824",
        pages: 320,
        language: "English",
        publishedDate: "2022-08-09",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781982185824-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781982185824-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Taste",
        author: "Stanley Tucci",
        description: "A beautiful exploration of life through the lens of food and cooking.",
        price: 499,
        category: "Biography",
        genre: "Entertainment",
        stock: 85,
        isbn: "9781982168018",
        pages: 320,
        language: "English",
        publishedDate: "2021-10-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781982168018-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781982168018-L.jpg"
    },
    {
        title: "The Light We Carry",
        author: "Michelle Obama",
        description: "Michelle Obama shares her wisdom and tools for navigating change and challenge.",
        price: 549,
        category: "Biography",
        genre: "Inspirational",
        stock: 120,
        isbn: "9780593237465",
        pages: 336,
        language: "English",
        publishedDate: "2022-11-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593237465-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593237465-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Surely You're Joking, Mr. Feynman!",
        author: "Richard P. Feynman",
        description: "The hilarious and thought-provoking adventures of a curious physicist.",
        price: 349,
        category: "Biography",
        genre: "Science",
        stock: 75,
        isbn: "9780393316049",
        pages: 352,
        language: "English",
        publishedDate: "1985-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780393316049-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780393316049-L.jpg"
    },
    {
        title: "My Inventions",
        author: "Nikola Tesla",
        description: "The autobiography of the brilliant and eccentric inventor who envisioned the future.",
        price: 249,
        category: "Biography",
        genre: "Science",
        stock: 60,
        isbn: "9781604595307",
        pages: 104,
        language: "English",
        publishedDate: "1919-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781604595307-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781604595307-L.jpg"
    },
    {
        title: "The Story of My Life",
        author: "Helen Keller",
        description: "The inspiring journey of a woman who overcame blindness and deafness to become an author and activist.",
        price: 199,
        category: "Biography",
        genre: "Inspirational",
        stock: 100,
        isbn: "9780486292496",
        pages: 240,
        language: "English",
        publishedDate: "1903-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780486292496-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780486292496-L.jpg"
    },
    {
        title: "Up from Slavery",
        author: "Booker T. Washington",
        description: "An autobiography detailing the author's journey from a childhood in slavery to establishing a school for vocational training.",
        price: 249,
        category: "Biography",
        genre: "History",
        stock: 50,
        isbn: "9780486287386",
        pages: 256,
        language: "English",
        publishedDate: "1901-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780486287386-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780486287386-L.jpg"
    },
    {
        title: "The Soul of a Bird",
        author: "Evelyn Smith",
        description: "A beautiful exploration of the connection between nature and the human spirit.",
        price: 399,
        category: "Biography",
        genre: "Inspirational",
        stock: 40,
        isbn: "9781501175473",
        pages: 288,
        language: "English",
        publishedDate: "2024-02-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501175473-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501175473-L.jpg"
    },
    {
        title: "Paris: The Memoir",
        author: "Paris Hilton",
        description: "Paris Hilton's personal story about her life, fame, and reclaiming her power.",
        price: 499,
        category: "Biography",
        genre: "Entertainment",
        stock: 95,
        isbn: "9780063224612",
        pages: 336,
        language: "English",
        publishedDate: "2023-03-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780063224612-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780063224612-L.jpg"
    },
    {
        title: "Knife",
        author: "Salman Rushdie",
        description: "Rushdie's powerful and deeply personal account of the attack on his life and his recovery.",
        price: 549,
        category: "Biography",
        genre: "Human Rights",
        stock: 65,
        isbn: "9780593730248",
        pages: 224,
        language: "English",
        publishedDate: "2024-04-16",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593730248-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593730248-L.jpg",
        featured: true
    },
    {
        title: "My Name is Barbra",
        author: "Barbra Streisand",
        description: "The long-awaited memoir by the iconic singer, actress, and director.",
        price: 699,
        category: "Biography",
        genre: "Entertainment",
        stock: 100,
        isbn: "9780525429524",
        pages: 992,
        language: "English",
        publishedDate: "2023-11-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780525429524-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780525429524-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Tanya's Story",
        author: "Tanya Smith",
        description: "The incredible true story of a woman who built a fraudulent empire and lost it all.",
        price: 479,
        category: "Biography",
        genre: "True Crime",
        stock: 45,
        isbn: "9780063319042",
        pages: 352,
        language: "English",
        publishedDate: "2024-05-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780063319042-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780063319042-L.jpg"
    }
];

const seedBiography = async () => {
    try {
        console.log('Seeding 40 Biography books...');
        await Book.insertMany(biographyBooks);
        console.log('Successfully seeded 40 biography books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding biography books:', error);
        process.exit(1);
    }
};

seedBiography();
