import mongoose from 'mongoose';
import dotenv from 'dotenv';
import connectDB from './config/db.js';
import Book from './models/Book.js';

dotenv.config({ path: './server/.env' });
connectDB();

const selfHelpBooks = [
    {
        title: "How to Win Friends and Influence People",
        author: "Dale Carnegie",
        description: "The classic guide to improving your interpersonal skills and becoming more persuasive.",
        price: 349,
        category: "Self-Help",
        genre: "Communication",
        stock: 150,
        isbn: "9780671027032",
        pages: 288,
        language: "English",
        publishedDate: "1936-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        description: "A philosophy of success based on the success secrets of the wealthiest people of his time.",
        price: 299,
        category: "Self-Help",
        genre: "Success",
        stock: 130,
        isbn: "9781585424337",
        pages: 238,
        language: "English",
        publishedDate: "1937-03-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
        bestseller: true
    },
    {
        title: "The Alchemist",
        author: "Paulo Coelho",
        description: "A beautiful fable about following your dreams and listening to your heart.",
        price: 399,
        category: "Self-Help",
        genre: "Inspirational",
        stock: 200,
        isbn: "9780062315007",
        pages: 208,
        language: "English",
        publishedDate: "1988-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Daring Greatly",
        author: "Brené Brown",
        description: "How the courage to be vulnerable transforms the way we live, love, parent, and lead.",
        price: 449,
        category: "Self-Help",
        genre: "Personal Growth",
        stock: 90,
        isbn: "9781592408412",
        pages: 320,
        language: "English",
        publishedDate: "2012-09-11",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781592408412-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781592408412-L.jpg",
        bestseller: true
    },
    {
        title: "The Four Agreements",
        author: "Don Miguel Ruiz",
        description: "A practical guide to personal freedom based on ancient Toltec wisdom.",
        price: 325,
        category: "Self-Help",
        genre: "Spirituality",
        stock: 110,
        isbn: "9781878424310",
        pages: 160,
        language: "English",
        publishedDate: "1997-11-07",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781878424310-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781878424310-L.jpg",
        bestseller: true
    },
    {
        title: "You Are a Badass",
        author: "Jen Sincero",
        description: "How to stop doubting your greatness and start living an awesome life.",
        price: 399,
        category: "Self-Help",
        genre: "Empowerment",
        stock: 100,
        isbn: "9780762447695",
        pages: 256,
        language: "English",
        publishedDate: "2013-04-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780762447695-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780762447695-L.jpg",
        bestseller: true
    },
    {
        title: "Big Magic",
        author: "Elizabeth Gilbert",
        description: "Creative living beyond fear, encouraging readers to embrace their curiosity.",
        price: 425,
        category: "Self-Help",
        genre: "Creativity",
        stock: 80,
        isbn: "9781594634727",
        pages: 288,
        language: "English",
        publishedDate: "2015-09-22",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781594634727-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781594634727-L.jpg"
    },
    {
        title: "The 5 AM Club",
        author: "Robin Sharma",
        description: "Own your morning, elevate your life. A guide to maximizing productivity and well-being.",
        price: 499,
        category: "Self-Help",
        genre: "Productivity",
        stock: 120,
        isbn: "9781443456623",
        pages: 336,
        language: "English",
        publishedDate: "2018-12-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781443456623-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781443456623-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Ikigai",
        author: "Héctor García and Francesc Miralles",
        description: "The Japanese secret to a long and happy life by finding your purpose.",
        price: 379,
        category: "Self-Help",
        genre: "Hygge & Lifestyle",
        stock: 150,
        isbn: "9780143130727",
        pages: 208,
        language: "English",
        publishedDate: "2017-08-29",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "The Daily Stoic",
        author: "Ryan Holiday",
        description: "366 meditations on wisdom, perseverance, and the art of living.",
        price: 449,
        category: "Self-Help",
        genre: "Philosophy",
        stock: 100,
        isbn: "9780735211735",
        pages: 416,
        language: "English",
        publishedDate: "2016-10-18",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780735211735-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780735211735-L.jpg",
        bestseller: true
    },
    {
        title: "Can't Hurt Me",
        author: "David Goggins",
        description: "Master your mind and defy the odds. A memoir and guide to mental toughness.",
        price: 549,
        category: "Self-Help",
        genre: "Motivation",
        stock: 110,
        isbn: "9781544512280",
        pages: 364,
        language: "English",
        publishedDate: "2018-12-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781544512280-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781544512280-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "Mindset",
        author: "Carol S. Dweck",
        description: "The new psychology of success, exploring the power of a growth mindset.",
        price: 399,
        category: "Self-Help",
        genre: "Psychology",
        stock: 95,
        isbn: "9780345472328",
        pages: 320,
        language: "English",
        publishedDate: "2006-02-28",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg",
        bestseller: true
    },
    {
        title: "The Body Keeps the Score",
        author: "Bessel van der Kolk",
        description: "Brain, mind, and body in the healing of trauma.",
        price: 499,
        category: "Self-Help",
        genre: "Psychology",
        stock: 120,
        isbn: "9780143127741",
        pages: 464,
        language: "English",
        publishedDate: "2014-09-25",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "12 Rules for Life",
        author: "Jordan B. Peterson",
        description: "An antidote to chaos, offering profound and practical principles for living.",
        price: 525,
        category: "Self-Help",
        genre: "Philosophy",
        stock: 85,
        isbn: "9780345816022",
        pages: 448,
        language: "English",
        publishedDate: "2018-01-23",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780345816022-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780345816022-L.jpg",
        bestseller: true
    },
    {
        title: "Essentialism",
        author: "Greg McKeown",
        description: "The disciplined pursuit of less, helping you regain control of your choices.",
        price: 449,
        category: "Self-Help",
        genre: "Productivity",
        stock: 75,
        isbn: "9780804137386",
        pages: 272,
        language: "English",
        publishedDate: "2014-04-15",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780804137386-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780804137386-L.jpg"
    },
    {
        title: "The Gifts of Imperfection",
        author: "Brené Brown",
        description: "Let go of who you think you're supposed to be and embrace who you are.",
        price: 349,
        category: "Self-Help",
        genre: "Personal Growth",
        stock: 80,
        isbn: "9781592858491",
        pages: 160,
        language: "English",
        publishedDate: "2010-08-27",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781592858491-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781592858491-L.jpg"
    },
    {
        title: "Crucial Conversations",
        author: "Joseph Grenny et al.",
        description: "Tools for talking when stakes are high, improving communication and relationships.",
        price: 425,
        category: "Self-Help",
        genre: "Communication",
        stock: 65,
        isbn: "9780071771320",
        pages: 304,
        language: "English",
        publishedDate: "2002-06-18",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780071771320-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780071771320-L.jpg"
    },
    {
        title: "Emotional Intelligence",
        author: "Daniel Goleman",
        description: "Why it can matter more than IQ, exploring the importance of self-awareness and empathy.",
        price: 399,
        category: "Self-Help",
        genre: "Psychology",
        stock: 90,
        isbn: "9780553095036",
        pages: 352,
        language: "English",
        publishedDate: "1995-09-27",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780553095036-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780553095036-L.jpg"
    },
    {
        title: "The Obstacle Is the Way",
        author: "Ryan Holiday",
        description: "The timeless art of turning trials into triumph based on Stoic philosophy.",
        price: 399,
        category: "Self-Help",
        genre: "Philosophy",
        stock: 85,
        isbn: "9781591846352",
        pages: 224,
        language: "English",
        publishedDate: "2014-05-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781591846352-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781591846352-L.jpg",
        bestseller: true
    },
    {
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        description: "What the rich teach their kids about money that the poor and middle class do not.",
        price: 449,
        category: "Self-Help",
        genre: "Personal Finance",
        stock: 180,
        isbn: "9781612680194",
        pages: 336,
        language: "English",
        publishedDate: "1997-04-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781612681146-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
        featured: true,
        bestseller: true
    },
    {
        title: "The Millionaire Next Door",
        author: "Thomas J. Stanley",
        description: "The surprising secrets of America's wealthy and how they built their fortunes.",
        price: 349,
        category: "Self-Help",
        genre: "Personal Finance",
        stock: 70,
        isbn: "9781589795471",
        pages: 272,
        language: "English",
        publishedDate: "1996-10-28",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781589795471-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781589795471-L.jpg"
    },
    {
        title: "Keep Sharp",
        author: "Sanjay Gupta",
        description: "Build a better brain at any age, exploring cognitive health and longevity.",
        price: 499,
        category: "Self-Help",
        genre: "Health",
        stock: 60,
        isbn: "9781501166730",
        pages: 336,
        language: "English",
        publishedDate: "2021-01-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781501166730-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781501166730-L.jpg"
    },
    {
        title: "Mastery",
        author: "Robert Greene",
        description: "Examining the lives of historical figures to uncover the path to greatness.",
        price: 549,
        category: "Self-Help",
        genre: "Personal Growth",
        stock: 55,
        isbn: "9780670024964",
        pages: 352,
        language: "English",
        publishedDate: "2012-11-13",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780670024964-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780670024964-L.jpg"
    },
    {
        title: "The 48 Laws of Power",
        author: "Robert Greene",
        description: "A comprehensive guide to the tactics of power and influence.",
        price: 599,
        category: "Self-Help",
        genre: "Success",
        stock: 150,
        isbn: "9780140280197",
        pages: 452,
        language: "English",
        publishedDate: "1998-09-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780140280197-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780140280197-L.jpg",
        bestseller: true
    },
    {
        title: "Everything is F*cked",
        author: "Mark Manson",
        description: "A book about hope, exploring our modern anxieties and search for meaning.",
        price: 399,
        category: "Self-Help",
        genre: "Philosophy",
        stock: 120,
        isbn: "9780062888433",
        pages: 288,
        language: "English",
        publishedDate: "2019-05-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780062888433-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780062888433-L.jpg",
        bestseller: true
    },
    {
        title: "Make Your Bed",
        author: "William H. McRaven",
        description: "Little things that can change your life... and maybe the world.",
        price: 299,
        category: "Self-Help",
        genre: "Motivation",
        stock: 100,
        isbn: "9781455570249",
        pages: 144,
        language: "English",
        publishedDate: "2017-04-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781455570249-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781455570249-L.jpg",
        bestseller: true
    },
    {
        title: "Silence",
        author: "Erling Kagge",
        description: "In the age of noise, exploring the power and beauty of silence.",
        price: 349,
        category: "Self-Help",
        genre: "Spirituality",
        stock: 50,
        isbn: "9781524733230",
        pages: 160,
        language: "English",
        publishedDate: "2017-10-03",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781524733230-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781524733230-L.jpg"
    },
    {
        title: "The Art of Happiness",
        author: "Dalai Lama",
        description: "A guide to finding inner peace and joy in everyday life.",
        price: 399,
        category: "Self-Help",
        genre: "Spirituality",
        stock: 75,
        isbn: "9781573221115",
        pages: 352,
        language: "English",
        publishedDate: "1998-10-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781573221115-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781573221115-L.jpg"
    },
    {
        title: "Peak",
        author: "Anders Ericsson and Robert Pool",
        description: "Secrets from the new science of expertise, exploring deliberate practice.",
        price: 449,
        category: "Self-Help",
        genre: "Psychology",
        stock: 60,
        isbn: "9780544456235",
        pages: 336,
        language: "English",
        publishedDate: "2016-04-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780544456235-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780544456235-L.jpg"
    },
    {
        title: "Range",
        author: "David Epstein",
        description: "Why generalists triumph in a specialized world.",
        price: 499,
        category: "Self-Help",
        genre: "Success",
        stock: 65,
        isbn: "9780735214484",
        pages: 352,
        language: "English",
        publishedDate: "2019-05-28",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780735214484-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780735214484-L.jpg",
        featured: true
    },
    {
        title: "Indistractable",
        author: "Nir Eyal",
        description: "How to control your attention and choose your life.",
        price: 449,
        category: "Self-Help",
        genre: "Productivity",
        stock: 70,
        isbn: "9781948836531",
        pages: 304,
        language: "English",
        publishedDate: "2019-09-10",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781948836531-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781948836531-L.jpg"
    },
    {
        title: "Digital Minimalism",
        author: "Cal Newport",
        description: "Choosing a focused life in a noisy world, rethinking our relationship with technology.",
        price: 449,
        category: "Self-Help",
        genre: "Productivity",
        stock: 80,
        isbn: "9780525536512",
        pages: 304,
        language: "English",
        publishedDate: "2019-02-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780525536512-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780525536512-L.jpg",
        bestseller: true
    },
    {
        title: "The Comfort Book",
        author: "Matt Haig",
        description: "A collection of notes, lists, and stories written over several years as reminders that things are not always as dark as they may seem.",
        price: 399,
        category: "Self-Help",
        genre: "Inspirational",
        stock: 95,
        isbn: "9780143136668",
        pages: 272,
        language: "English",
        publishedDate: "2021-07-06",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780143136668-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780143136668-L.jpg"
    },
    {
        title: "Slow Productivity",
        author: "Cal Newport",
        description: "The lost art of accomplishment without burnout.",
        price: 529,
        category: "Self-Help",
        genre: "Productivity",
        stock: 50,
        isbn: "9780593544853",
        pages: 256,
        language: "English",
        publishedDate: "2024-03-05",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593544853-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593544853-L.jpg",
        featured: true
    },
    {
        title: "Scarcity Brain",
        author: "Michael Easter",
        description: "Fix your craving mindset and live in the land of plenty.",
        price: 499,
        category: "Self-Help",
        genre: "Psychology",
        stock: 45,
        isbn: "9780593236597",
        pages: 352,
        language: "English",
        publishedDate: "2023-09-26",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593236597-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593236597-L.jpg"
    },
    {
        title: "Real Self-Care",
        author: "Pooja Lakshmin",
        description: "A transformative program for redefining wellness and reclaiming your life.",
        price: 479,
        category: "Self-Help",
        genre: "Health",
        stock: 40,
        isbn: "9780143136828",
        pages: 304,
        language: "English",
        publishedDate: "2023-03-14",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780143136828-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780143136828-L.jpg"
    },
    {
        title: "The Perfectionist's Guide to Losing Control",
        author: "Katherine Morgan Schafler",
        description: "A guide for women to embrace their perfectionism and use it for good.",
        price: 449,
        category: "Self-Help",
        genre: "Personal Growth",
        stock: 35,
        isbn: "9780593330104",
        pages: 336,
        language: "English",
        publishedDate: "2023-01-17",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593330104-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593330104-L.jpg"
    },
    {
        title: "Build the Life You Want",
        author: "Arthur C. Brooks and Oprah Winfrey",
        description: "The art and science of getting happier.",
        price: 549,
        category: "Self-Help",
        genre: "Inspirational",
        stock: 130,
        isbn: "9780593545409",
        pages: 272,
        language: "English",
        publishedDate: "2023-09-12",
        coverImage: "https://covers.openlibrary.org/b/isbn/9780593545409-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9780593545409-L.jpg",
        bestseller: true
    },
    {
        title: "Good Vibes, Good Life",
        author: "Vex King",
        description: "How self-love is the key to unlocking your greatness.",
        price: 349,
        category: "Self-Help",
        genre: "Inspirational",
        stock: 150,
        isbn: "9781788171823",
        pages: 304,
        language: "English",
        publishedDate: "2018-12-04",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781788171823-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781788171823-L.jpg",
        bestseller: true
    },
    {
        title: "Manifest",
        author: "Roxy Nafousi",
        description: "7 steps to living your best life, exploring the power of manifestation.",
        price: 399,
        category: "Self-Help",
        genre: "Spirituality",
        stock: 110,
        isbn: "9781841885421",
        pages: 192,
        language: "English",
        publishedDate: "2022-01-01",
        coverImage: "https://covers.openlibrary.org/b/isbn/9781841885421-L.jpg",
        image_url: "https://covers.openlibrary.org/b/isbn/9781841885421-L.jpg"
    }
];

const seedSelfHelp = async () => {
    try {
        console.log('Seeding 40 Self-Help books...');
        await Book.insertMany(selfHelpBooks);
        console.log('Successfully seeded 40 self-help books!');
        process.exit();
    } catch (error) {
        console.error('Error seeding self-help books:', error);
        process.exit(1);
    }
};

seedSelfHelp();
